(function(){var l=document.createElement('link');l.rel='icon';l.type='image/x-icon';l.href='favicon.ico';document.head.appendChild(l)})();

const $=i=>document.getElementById(i),cl=(v,a=0,b=100)=>Math.max(a,Math.min(b,v)),rn=(a,b)=>a+Math.random()*(b-a),pk=a=>a[Math.random()*a.length|0];
const R=n=>{n=Math.round(n);const a=Math.abs(n);return(n<0?'-':'')+'Rp '+(a>=1e24?(a/1e24).toFixed(2)+' Sp':a>=1e21?(a/1e21).toFixed(2)+' Sk':a>=1e18?(a/1e18).toFixed(2)+' Kn':a>=1e15?(a/1e15).toFixed(2)+' Kd':a>=1e12?(a/1e12).toFixed(2)+' T':a>=1e9?(a/1e9).toFixed(2)+' M':a>=1e6?(a/1e6).toFixed(2)+' jt':a.toLocaleString('id-ID'))};
const DN=['Sen','Sel','Rab','Kam','Jum','Sab','Min'];
const H=[['Kos',25e3],['Kontrakan',70e3],['Apartemen',180e3],['Rumah sewa',350e3],['Rumah mewah',900e3]],F=[['Hemat',25e3],['Normal',55e3],['Premium',130e3],['Restoran & chef',300e3]],I=[['Tanpa asuransi',0],['BPJS',8e3],['Asuransi swasta',35e3],['Asuransi premium',80e3]];
const TR=[['Jalan kaki / sepeda',0,1,.4,0],['Angkutan umum',15e3,1,.2,0],['Motor',35e3,0,.1,0],['Ojek / taksi online',60e3,0,0,.05],['Mobil pribadi',150e3,0,-.2,.1]],
IT=[['Kuota hemat',5e3,0],['Paket standar',12e3,.05],['Internet cepat',25e3,.1]],
EN=[['Tanpa langganan',0,0],['Streaming',8e3,.1],['Paket hiburan lengkap',20e3,.2]],
LK=[['Seadanya',5e3,0,0],['Rapi',15e3,.05,.03],['Branded',40e3,.1,.06]],
GM=[['Tanpa kebugaran',0,0,0],['Gym',15e3,.15,.3],['Personal trainer',60e3,.3,.6]],
DON=[['Tidak',0],['2,5% dari pemasukan',.025],['5% dari pemasukan',.05]],
qf=i=>Math.min(i,2)+Math.max(0,i-2)*.4;
const AS=[['BNUS','Bank Nusantara','Saham',9000,.02],['TLKM','Telko Raya','Saham',3800,.018],['GOTO','Gojek Tech','Saham',80,.05],['ANTM','Tambang Emas','Saham',1600,.03],['XAU','Emas (gram)','Komoditas',1.3e6,.01],['OIL','Minyak Mentah','Komoditas',1.1e6,.025],['KPI','Kopi Arabika','Komoditas',95e3,.02],['BTC','Bitcoin','Kripto',1e9,.06],['ETH','Ethereum','Kripto',5e7,.07],['BRPT','Petrokimia Nusantara','Saham',5200,.022],['SOL','Solana','Kripto',3.2e6,.08],['USDIDR','Dolar AS','Forex',15800,.007],['EURIDR','Euro','Forex',17200,.008],['SGDIDR','Dolar Singapura','Forex',11700,.006]];
const NW=[['Bank Sentral menurunkan suku bunga','Ekonomi','Saham',.006,8,.05],['Inflasi global melonjak','Ekonomi','Komoditas',.005,8,-.05],['Harga minyak naik akibat konflik','Politik','OIL',.012,6,-.03],['Panen kopi gagal di Brasil','Ekonomi','KPI',.015,6,0],['Regulator memperketat aturan kripto','Politik','Kripto',-.02,6,-.02],['Institusi besar memborong Bitcoin','Ekonomi','BTC',.02,5,.02],['Resesi dunia mengancam','Ekonomi','Saham',-.012,10,-.1],['Ekonomi tumbuh melampaui target','Ekonomi','Saham',.008,10,.1],['Ketegangan geopolitik, emas jadi safe haven','Politik','XAU',.01,8,0],['Subsidi UMKM diumumkan pemerintah','Politik','Saham',.003,6,.1],['Skandal korupsi guncang bursa','Politik','Saham',-.01,5,-.04],['Booming properti di kota besar','Ekonomi','PROP',.004,15,.03]];
const JB=[['Pelayan Kafe',120e3,{},0],['Staf Admin',200e3,{com:1},0],['Programmer Junior',350e3,{tech:2},1],['Analis Keuangan',500e3,{fin:3},2],['Manajer Operasional',800e3,{biz:4,com:3},3],['Sales Lapangan',170e3,{mkt:1},0],['Asisten Desainer',180e3,{des:1},0],['Teknisi Lapangan',300e3,{eng:2},1],['Content Creator',320e3,{des:2,mkt:1},1],['Staf Legal Junior',340e3,{law:2},1],['Staf Ekspor-Impor',480e3,{lang:3,biz:1},2],['Insinyur Proyek',550e3,{eng:4,biz:2},2],['Marketing Manager',560e3,{mkt:4,com:2},2],['Konsultan Hukum Korporat',850e3,{law:6,fin:2},3],['Direktur Kreatif',820e3,{des:6,mkt:3},3]];
const SKN={biz:'Manajemen Bisnis',fin:'Keuangan & Investasi',com:'Komunikasi',tech:'Teknologi',mkt:'Pemasaran',des:'Desain Kreatif',eng:'Teknik & Produksi',law:'Hukum & Kepatuhan',lang:'Bahasa Asing'},SKD={biz:'Bisnis lebih efisien & laris',fin:'Fee trading, bunga deposito & kredit lebih baik',com:'Gaji dan jaringan lebih baik',tech:'Freelance lebih mahal, syarat kerja IT',mkt:'Permintaan bisnis +3% per level, popularitas naik lebih cepat',des:'Freelance lebih mahal, produk bisnis lebih menarik',eng:'Biaya produksi bisnis lebih murah',law:'Pajak bisnis lebih kecil, risiko suap turun',lang:'Jaringan tumbuh lebih cepat, investor lebih mudah dilobi'};
const PR=[['Kamar Kos (5 pintu)',150e6,.07],['Apartemen Studio',500e6,.06],['Rumah Tinggal',1.2e9,.05],['Ruko Komersial',3e9,.08],['Gedung Perkantoran',15e9,.09],['Kios Pasar',40e6,.08],['Rumah Kontrakan Petak',280e6,.075],['Vila Liburan',2e9,.065],['Kawasan Pergudangan',6e9,.085],['Hotel Butik',25e9,.095]];
const PRK=['kos','apt','rumah','ruko','gedung','kios','kontrakan','vila','gudang','hotel'],PRB=[[.75,8],[.75,20],[.75,12],[.75,18],[.75,35],[.75,5],[.75,10],[.75,16],[.75,22],[.75,45]];
const PM=[['Jalan Tol Antarkota',80e9,.10,60,40,40,1,'tol'],['Pelabuhan Niaga',250e9,.11,90,55,50,2,'pelabuhan'],['Bandara Regional',750e9,.12,120,65,60,3,'bandara'],['Kawasan Ekonomi Khusus',2e12,.13,150,75,70,4,'kek'],['Kota Mandiri',6e12,.15,200,85,80,5,'kota']];
const BD=[['ORI Negara',.06,180,0],['Sukuk Ritel',.07,120,.01],['Obligasi Korporasi',.11,90,.15]];
const ST=[['Asisten Pribadi',120e3,'+2 jam waktu per hari'],['Akuntan',150e3,'Biaya operasional bisnis -10%'],['Manajer Pemasaran',150e3,'Permintaan bisnis +15%, popularitas naik'],['Sekretaris',100e3,'Jaringan tumbuh 2x lebih cepat'],['Dokter Pribadi',200e3,'Kesehatan pulih tiap hari, tanpa biaya sakit']];
const OF=[['Ketua RT',20,10,2e6,20e3],['Anggota DPRD',40,30,50e6,150e3],['Wali Kota',60,50,500e6,400e3],['Gubernur',75,70,3e9,1e6],['Presiden',90,85,20e9,4e6]];
const GL=[['Punya kekayaan Rp 100 jt',()=>nw()>=1e8],['Dirikan bisnis pertama',()=>S.bizs.length],['Kekayaan Rp 1 Miliar',()=>nw()>=1e9],['Punya properti',()=>S.props.length],['Punya obligasi / deposito',()=>S.bonds.length||S.dep>0],['Kepopuleran 70+',()=>S.pop>=70],['Melakukan IPO bisnis pertama',()=>S.bizs.some(b=>b.ipo)],['Membangun megaproyek negara',()=>S.megas.length>0],['Skill Manajemen Bisnis level 5',()=>S.sk.biz>=5],['Menjabat di politik',()=>S.office>0],['Punya bisnis skala Nasional',()=>S.bizs.some(b=>b.sc>=5)],['Kelola 3 bisnis sekaligus',()=>S.bizs.length>=3],[' SASARAN AKHIR: Kekayaan Rp 10 Miliar',()=>nw()>=1e10]];
const T=[['portfolio','','Portofolio'],['news','','Berita'],['exp','','Pengeluaran'],['skills','','Skill'],['trade','','Trading'],['job','','Kerja'],['biz','','Bisnis'],['leis','','Waktu Luang'],['prop','','Properti'],['bond','','Obligasi'],['netw','','Jaringan'],['pop','⭐','Popularitas'],['goal','','Sasaran'],['pol','','Politik'],['staff','','Staf'],['bank','','Bank'],['lelang','','Pelelangan']];
const BT=[['Kafe & Kuliner',30e3,.42,1.2,'mkt',1],['Toko Ritel',40e3,.42,1.1,'biz',1.2],['Jasa Digital',60e3,.28,.7,'tech',1],['Manufaktur',150e3,.55,.6,'eng',2],['Agensi Kreatif',80e3,.35,.6,'des',1.3],['Ekspor-Impor',100e3,.5,.6,'lang',1.5],['Konsultan Hukum & Pajak',90e3,.3,.55,'law',1.1]],
SC=[['Mikro',1,15e6,1],['Kecil',3.5,60e6,1],['Menengah',10,200e6,2],['Besar',28,600e6,2],['Sangat Besar',75,1.8e9,3],['Nasional',200,5e9,3],['Internasional',500,15e9,4]],NB={ty:0,sc:0,mg:'self',name:''},bcap=b=>SC[b.sc][2]*BT[b.ty][5];
const BG={pedagang:{cash:8e6,net:10,sk:{biz:1}},kampus:{cash:3e6,sk:{fin:1,com:1,tech:1}},pejabat:{cash:5e6,net:25,pop:20},rantau:{cash:1e6,hp:95,str:10,job:0},coder:{cash:2e6,sk:{tech:3}}},BGN={pedagang:'Anak Pedagang',kampus:'Lulusan Kampus',pejabat:'Anak Pejabat',rantau:'Anak Rantau',coder:'Programmer Otodidak'};
let S,tab=null,BV=null,BMK='local',TV=null,PV=null;
function init(bg,nm){S={d:0,cash:5e6,hp:80,hap:60,str:20,pop:10,net:5,hrs:10,mg:0,sk:{biz:0,fin:0,com:0,tech:0},house:0,food:1,ins:0,job:null,bizs:[],bn:0,tr:1,it:1,en:0,lk:0,gm:0,dn:0,hold:{},px:{},pv:{},props:[],pi:1,bonds:[],dep:0,loan:0,staff:[],office:0,camp:null,tax:.1,eco:1,news:[],logs:[],fx:[],ex:{},inc:{},bl:null,won:0,over:0,m1b:0,auc:{items:[],nextId:1,hist:[]},collect:[],dia:0,diaGiven:0};AS.forEach(a=>S.px[a[0]]=a[3]);const b=BG[bg]||{};for(const k in b)k=='sk'?Object.assign(S.sk,b.sk):S[k]=b[k];if(S.job!=null)S.hrs-=6;S.bg=bg;S.uname=(nm||'').toString().trim().slice(0,30);S.logs=['Hari 0: Latar belakang: '+(BGN[bg]||'-')+(S.uname?' · '+S.uname:'')]}
try{const nb=localStorage.getItem('t19new');if(nb){localStorage.removeItem('t19new');let bgv=nb,nmv='';try{const o=JSON.parse(nb);if(o&&typeof o=='object'){bgv=o.bg;nmv=o.name||''}}catch(e){}init(bgv,nmv)}else S=JSON.parse(localStorage.getItem('t19'))}catch(e){}if(!S)init('kampus');for(const k in SKN)S.sk[k]=S.sk[k]||0;S.orders=S.orders||[];S.shorts=S.shorts||{};S.thist=S.thist||[];S.megas=S.megas||[];S.megaBuilds=S.megaBuilds||[];S.builds=S.builds||[];if(S.uname==null)S.uname='';if(S.m1b==null)S.m1b=0;if(S.biz&&!S.bizs){const o=S.biz;S.bizs=[{id:1,ty:1,name:'Usaha Lama',sc:Math.min(6,o.lv-1),mgmt:'self',price:o.price,qual:o.qual,mk:o.mkt>=4e5?2:o.mkt>=1e5?1:0,mg:0}];S.bn=1;delete S.biz}if(!S.bizs)S.bizs=[];if(S.tr==null)Object.assign(S,{tr:1,it:1,en:0,lk:0,gm:0,dn:0});if(!S.auc)S.auc={items:[],nextId:1,hist:[]};if(!S.collect)S.collect=[];if(S.dia==null)S.dia=0;if(S.diaGiven==null)S.diaGiven=0;
try{const o=JSON.parse(localStorage.getItem('t19opt')||'{}');if(o.th)document.documentElement.dataset.theme=o.th;if(o.zm)document.body.style.zoom=o.zm}catch(e){}
const sv=()=>{try{localStorage.setItem('t19',JSON.stringify(S))}catch(e){}};
const log=m=>{S.logs.unshift('Hari '+S.d+': '+m);S.logs.length=Math.min(S.logs.length,30)};
const uN=()=>S.uname&&S.uname.trim()?S.uname.trim():'Seorang pengusaha muda';
const bigNews=(t,cat,up)=>{S.news.unshift({d:S.d,t,c:cat||'Sorotan',up:up!==false});if(S.news.length>40)S.news.length=40};
const st=n=>S.staff.includes(n)?1:0,use=h=>S.hrs>=h?(S.hrs-=h,1):(log(' Waktu hari ini tidak cukup ('+h+' jam)'),0),pay=a=>S.cash>=a?(S.cash-=a,1):(log(' Uang tidak cukup'),0);
function nw(){let v=S.cash+S.dep-S.loan;AS.forEach(a=>{const h=S.hold[a[0]];if(h)v+=h.q*S.px[a[0]]});S.props.forEach(i=>v+=PR[i][1]*S.pi);S.bonds.forEach(b=>v+=b.amt);S.bizs.forEach(b=>v+=bcap(b)*.6);return v}
function bizDay(b){b.auto=b.auto||0;const t=BT[b.ty],m=SC[b.sc][1],pm={.8:1.3,1:1,1.25:.75,1.5:.55}[b.price],ef=b.mgmt=='ceo'?.95:(b.mg?1.15:.6),ev=b.evtMult||1;let c=(12+S.pop/4)*m*t[3]*(.6+.4*S.eco)*(.7+.3*b.qual)*pm*(1+S.sk.biz*.02)*(1+S.sk[t[4]]*.03)*(1+S.sk.mkt*.015)*(1+S.sk.des*.01)*[1,1.12,1.3][b.mk]*(1+.15*st('Manajer Pemasaran'))*(1+S.net/200)*ef*(1+b.auto*.06)*ev;c=Math.round(c*rn(.85,1.15)*(1-S.str/300));const rev=c*t[1]*b.price,vc=c*t[1]*(t[2]+.08*b.qual)*(1-Math.min(.4,S.sk.biz*.03+S.sk.eng*.02)-.1*st('Akuntan')-b.auto*.05),fx=6e4*m+[0,1e5,4e5][b.mk]*m**.8+(b.mgmt=='ceo'?12e4*m**.9:0)+b.auto*4e4*m,pr=rev-vc-fx;b.evtMult=1;return{c,rev,pr,tax:pr>0?pr*S.tax*(1-S.sk.law*.03):0}}
function tick(){S.d++;const wd=S.d%7,wk=wd<5,ex={Sewa:H[S.house][1],Makan:F[S.food][1],Kesehatan:I[S.ins][1],Tagihan:15e3,Transportasi:TR[S.tr][1],Internet:IT[S.it][1],Hiburan:EN[S.en][1],Penampilan:LK[S.lk][1],Kebugaran:GM[S.gm][1],Staf:0,Pajak:0,Bunga:0,Donasi:0},inc={Gaji:0,Bisnis:0,'Sewa properti':0,'Bunga deposito':0,Kupon:0,Jabatan:0};
S.staff.forEach(n=>ex.Staf+=ST.find(s=>s[0]==n)[1]);
if(S.job!=null&&wk)inc.Gaji=JB[S.job][1]*(1-S.str/250)*(1+S.sk.com*.03+Object.entries(JB[S.job][2]).reduce((a,[k,v])=>a+Math.max(0,S.sk[k]-v)*.03,0));
const BEV=[['Pesanan besar mendadak',1,.18],['Ulasan positif viral',1,.15],['Kolaborasi dengan brand lain',1,.12],['Pemasok telat kirim barang',-1,.15],['Mesin/peralatan rusak',-1,.12],['Karyawan pesaing membajak pelanggan',-1,.1],['Sertifikasi kualitas diperoleh',1,.08],['Keluhan pelanggan viral',-1,.08]];
S.bizs.forEach(b=>{if(Math.random()<.08){const e=pk(BEV);b.evtMult=1+e[1]*rn(.15,.35);b.lastEvt='Hari '+S.d+': '+e[0]+' ('+(e[1]>0?'+':'')+Math.round((b.evtMult-1)*100)+'% permintaan hari ini)';log(b.name+' - '+e[0])}b.l=bizDay(b);ex.Pajak+=b.l.tax;let net=b.l.pr-b.l.tax;
if(b.ipo){b.ipo.pv=b.ipo.px;const pub=net*b.ipo.pct/100;net-=pub;const drift=(net>0?1:-1)*rn(.002,.02);b.ipo.px=Math.max(5,Math.round(b.ipo.px*(1+drift+rn(-.01,.01))))}
inc.Bisnis+=net;b.hist=b.hist||[];b.hist.push(net);if(b.hist.length>14)b.hist.shift()});
S.props.forEach(i=>inc['Sewa properti']+=PR[i][1]*PR[i][2]/365*S.pi);
if(S.builds&&S.builds.length)S.builds=S.builds.filter(b=>{if(S.d>=b.end){S.props.push(b.ty);log('Pembangunan '+PR[b.ty][0]+' selesai!');return false}return true});
S.megas.forEach(i=>inc['Sewa properti']+=PM[i][1]*PM[i][2]/365);
if(S.megaBuilds&&S.megaBuilds.length)S.megaBuilds=S.megaBuilds.filter(b=>{if(S.d>=b.end){S.megas.push(b.ty);log('Megaproyek '+PM[b.ty][0]+' rampung!');S.pop=cl(S.pop+8);bigNews(uN()+' merampungkan megaproyek '+PM[b.ty][0]+', mengubah wajah perekonomian daerah!','Infrastruktur',true);return false}return true});
const dr=(.04+S.sk.fin*.002)/365;inc['Bunga deposito']=S.dep*dr;S.dep+=inc['Bunga deposito'];
const lr=Math.max(.06,.12-S.sk.fin*.005-S.net*.0005)/365;ex.Bunga=S.loan*lr;S.loan+=ex.Bunga;ex.Bunga=0;
if(S.office)inc.Jabatan=OF[S.office-1][4];
S.bonds=S.bonds.filter(b=>{if((S.d-b.st)%30==0&&S.d>b.st){const k=b.amt*b.y/12;inc.Kupon+=k}if(S.d>=b.end){if(Math.random()<b.rk){log(' '+b.n+' gagal bayar! Modal hangus');return 0}S.cash+=b.amt;log(' '+b.n+' jatuh tempo, modal kembali');return 0}return 1});
if(Math.random()<.015){const c=S.ins||st('Dokter Pribadi')?3e5:2e6;ex.Kesehatan+=st('Dokter Pribadi')?0:c;S.hp-=st('Dokter Pribadi')?4:12;log(' Jatuh sakit')}
let i=0,o=0;for(const k in inc)i+=inc[k];ex.Donasi=Math.max(0,i)*DON[S.dn][1];for(const k in ex)o+=ex[k];S.cash+=i-o;S.ex=ex;S.inc=inc;
if(S.cash<0){S.loan+=-S.cash;S.cash=0;log(' Saldo minus, otomatis jadi pinjaman')}
S.str=cl(S.str+(S.job!=null&&wk?2:0)+Math.min(3,S.bizs.filter(b=>b.mgmt=='self').length*.6)-1.2);S.hap=cl(S.hap-.4+(qf(S.house)+qf(S.food))*.15-(S.str>70?.6:0));
S.hp=cl(S.hp+(qf(S.food)-1)*.25+(qf(S.house)-1)*.1-(S.str>75?1:0)+(S.food==0?-.2:.05)+st('Dokter Pribadi')*.3);S.pop=cl(S.pop-.1+st('Manajer Pemasaran')*.1);S.str=cl(S.str+(S.job!=null&&wk?TR[S.tr][3]:0)-GM[S.gm][3]);S.hap=cl(S.hap+TR[S.tr][4]+IT[S.it][2]+EN[S.en][2]+LK[S.lk][2]+.05*S.dn);S.hp=cl(S.hp+GM[S.gm][2]);S.pop=cl(S.pop+LK[S.lk][3]+.03*S.dn);
S.eco+=(1-S.eco)*.03+rn(-.01,.01);S.pi*=1+rn(-.003,.0035);S.fx=S.fx.filter(f=>--f.d>0);
if(Math.random()<.4){const n=pk(NW),rm=Math.random()<.4,fl=rm&&Math.random()<.35;const e=fl?-n[3]:n[3];S.fx.push({t:n[2],e,d:n[4]});S.eco=cl(S.eco+(fl?-n[5]:n[5]),.6,1.5);S.news.unshift({d:S.d,t:(rm?'Rumor: ':'')+n[0],c:rm?'Rumor':n[1],up:e>0});if(S.news.length>40)S.news.length=40}
AS.forEach(a=>{let e=0;S.fx.forEach(f=>{if(f.t==a[0]||f.t==a[2])e+=f.e});S.pv[a[0]]=S.px[a[0]];S.px[a[0]]=Math.max(1,S.px[a[0]]*(1+rn(-a[4],a[4])+e+.0002));const h=(S.hist=S.hist||{})[a[0]]||(S.hist[a[0]]=[S.pv[a[0]]]);h.push(S.px[a[0]]);if(h.length>40)h.shift()});
if(S.shorts)for(const id in S.shorts){const hh=S.shorts[id];hh.val-=hh.val*.001;if(hh.val<=0){delete S.shorts[id];log('Short '+id+' kena margin call')}}
if(S.orders&&S.orders.length)S.orders=S.orders.filter(o=>{const px=S.px[o.aid],hit=o.kind=='buy'?px<=o.price:px>=o.price;if(!hit)return true;if(o.kind=='buy'){if(S.cash<o.amt)return true;buy(o.aid,o.amt)}else{if(!S.hold[o.aid])return true;sell(o.aid,o.amt)}return false});
if(S.camp&&S.d>=S.camp.end){const o=OF[S.camp.i],ch=cl(.25+S.camp.sp/o[3]*.15+(S.pop-o[1])/200+(S.net-o[2])/300,.1,.9);if(Math.random()<ch){S.office=S.camp.i+1;S.pop=cl(S.pop+10);log(' Anda terpilih menjadi '+o[0]);bigNews(uN()+' terpilih menjadi '+o[0]+' lewat pemilihan!','Politik',true)}else log(' Anda kalah pemilihan '+o[0]);S.camp=null}
S.hrs=10+2*st('Asisten Pribadi')-(S.job!=null&&wk?6+TR[S.tr][2]:0);S.bizs.forEach(b=>b.mg=0);
aucTick();
if(S.hp<=0||nw()<-3e7){S.over=1;const sakit=S.hp<=0;bigNews(uN()+(sakit?' tutup usia di umur '+(19+(S.d/365|0))+' tahun setelah lama berjuang menjaga kesehatan.':' dinyatakan bangkrut total, seluruh aset disita untuk melunasi utang.'),sakit?'Duka':'Ekonomi',false);fin('Game Over',sakit?'Kesehatan Anda habis di usia '+(19+(S.d/365|0))+' tahun.':'Anda bangkrut dan terlilit utang.')}
else if(19+(S.d/365|0)>=60){S.over=1;S.retired=1;bigNews(uN()+' resmi memasuki masa pensiun di usia 60 tahun dengan kekayaan bersih '+R(nw())+'.','Sorotan',true);fin('Pensiun','Usia pensiun (60 tahun) tercapai di hari '+S.d+'. Kekayaan bersih akhir: '+R(nw())+'. Terima kasih sudah bermain — cek Portofolio untuk rekap lengkap.')}}
function fin(t,m,cont){$('ot').textContent=t;$('om').textContent=m;if($('ovc'))$('ovc').style.display=cont?'inline-block':'none';$('ov').style.display='flex'}
function nxt(n){for(let i=0;i<n&&!S.over;i++)tick();if(!S.m1b&&nw()>=1e9){S.m1b=1;bigNews(uN()+' menembus kekayaan Rp 1 Miliar!','Sorotan',true)}if(!S.won&&nw()>=1e10){S.won=1;bigNews(uN()+' resmi jadi miliarder, kekayaan tembus Rp 10 Miliar!','Sorotan',true);fin(' Anda Menang!','Kekayaan Rp 10 Miliar tercapai di usia '+(19+(S.d/365|0))+' tahun. Anda boleh lanjut bermain.',true)}if(!S.diaGiven&&GL.every(g=>g[1]())){S.diaGiven=1;S.dia=(S.dia||0)+10;log(' Semua sasaran tercapai! Anda meraih 10 berlian.');bigNews(uN()+' berhasil menuntaskan seluruh sasaran hidup dan meraih 10 berlian langka!','Sorotan',true)}ren()}
const bt=(l,f,d)=>`<button class="b" ${d?'disabled':''} onclick="${f};ren()">${l}</button>`,row=(a,b)=>`<div class="r"><div>${a}</div><div>${b}</div></div>`,card=(t,b)=>`<div class="c"><h3>${t}</h3>${b}</div>`;
const bar=(l,v,c)=>`<div class="s"><small>${l}: ${Math.round(v)}</small><div class="bar"><i style="width:${v}%;background:${c}"></i></div></div>`;
function buy(id,a){const f=a*(.003-Math.min(.002,S.sk.fin*.0002));if(!pay(a))return;const h=S.hold[id]||(S.hold[id]={q:0,c:0});h.q+=(a-f)/S.px[id];h.c+=a;log('Beli '+id+' '+R(a));S.thist=S.thist||[];S.thist.unshift('Hari '+S.d+' · Beli '+id+' · '+R(a));if(S.thist.length>30)S.thist.length=30}
function sell(id,p){const h=S.hold[id];if(!h)return;const q=h.q*p,v=q*S.px[id]*(1-.003);S.cash+=v;h.c*=1-p;h.q-=q;if(h.q<1e-9)delete S.hold[id];log('Jual '+id+' '+R(v));S.thist=S.thist||[];S.thist.unshift('Hari '+S.d+' · Jual '+id+' · '+R(v));if(S.thist.length>30)S.thist.length=30}
function course(k){const l=S.sk[k];if(l>=10)return;const c=3e5*(l+1)**1.5;if(S.hrs>=3&&S.cash>=c){pay(c);use(3);S.sk[k]++;S.hap=cl(S.hap+1);log(' '+SKN[k]+' naik ke level '+(l+1));maybeTalk('course','mentor',.3)}else log('Butuh '+R(c)+' dan 3 jam')}
function gig(k){const g={ojek:[3,()=>rn(1e5,2e5),4],free:[3,()=>(1.5e5+S.sk.tech*7e4+S.sk.des*5e4)*(1+S.it*.06),5],jual:[2,()=>rn(6e4,2.5e5)*(1+S.sk.biz*.1),3]}[k];if(!use(g[0]))return;const v=g[1]()*(1-S.str/300);S.cash+=v;S.str=cl(S.str+g[2]);log(' Kerja sampingan +'+R(v));maybeTalk('gig','client',.3)}
function leis(k){const o={hobi:[2,5e4,-10,6,0],rest:[4,0,-12,2,6],gym:[2,3e4,-4,2,3],lib:[10,3e6,-40,25,4]}[k];if(S.hrs<o[0])return log(' Waktu tidak cukup');if(!pay(o[1]))return;S.hrs-=o[0];S.str=cl(S.str+o[2]);S.hap=cl(S.hap+o[3]);S.hp=cl(S.hp+o[4]);if(k=='hobi'||k=='lib')maybeTalk('leis','friend',.3)}
function popa(k){const o={sos:[1,0,rn(1,3)],inf:[0,5e5,4],amal:[1,5e6,8],tv:[2,2e7,12]}[k];if(S.hrs<o[0])return log(' Waktu tidak cukup');if(!pay(o[1]))return;S.hrs-=o[0];S.pop=cl(S.pop+o[2]*(1+S.sk.mkt*.08));maybeTalk('popa','fan',.3)}
function bond(i,a){if(!pay(a))return;const b=BD[i];S.bonds.push({n:b[0],amt:a,y:b[1],st:S.d,end:S.d+b[2],rk:b[3]})}
function bank(k,a){if(k=='dep'){a=a=='all'?S.cash:a;if(S.cash>=a&&a>0){S.cash-=a;S.dep+=a}}else if(k=='wd'){S.cash+=S.dep;S.dep=0}else if(k=='loan'){const lim=Math.max(5e6,nw()*.5);if(S.loan+a<=lim){S.loan+=a;S.cash+=a}else log('Melebihi batas kredit '+R(lim))}else{const p=Math.min(S.cash,S.loan);S.cash-=p;S.loan-=p}}
function exchangeDia(n){n=Math.min(Math.round(n),S.dia||0);if(n<=0)return log('Tidak ada berlian untuk ditukar');S.dia-=n;S.cash+=n*5e6;log('Menukar '+n+' berlian menjadi '+R(n*5e6))}
function buyP(i){const p=PR[i][1]*S.pi;if(pay(p))S.props.push(i)}
function sellP(x){const i=S.props.splice(x,1)[0];S.cash+=PR[i][1]*S.pi*.97}
function startBuild(i){const p=PR[i],cost=Math.round(p[1]*S.pi*PRB[i][0]);if(!pay(cost))return;S.builds=S.builds||[];S.builds.push({ty:i,start:S.d,end:S.d+PRB[i][1],cost});log('Mulai membangun '+p[0]+', selesai '+PRB[i][1]+' hari lagi')}
function startMega(i){const p=PM[i];if(S.net<p[4])return log('Jaringan minimal '+p[4]+' dibutuhkan');if(S.pop<p[5])return log('Popularitas minimal '+p[5]+' dibutuhkan');if(S.office<p[6])return log('Perlu menjabat minimal '+OF[p[6]-1][0]);if(!pay(p[1]))return;S.megaBuilds=S.megaBuilds||[];S.megaBuilds.push({ty:i,start:S.d,end:S.d+p[3]});log('Memulai megaproyek: '+p[0]+', selesai '+p[3]+' hari lagi')}
function sellMega(x){const i=S.megas.splice(x,1)[0];const v=Math.round(PM[i][1]*.5);S.cash+=v;log('Melepas hak kelola '+PM[i][0]+' seharga '+R(v))}
function hire(n){const s=ST.find(x=>x[0]==n);if(S.staff.includes(n))S.staff=S.staff.filter(x=>x!=n);else{S.staff.push(n);if(n=='Asisten Pribadi')S.hrs+=2}}
function runP(i){const o=OF[i];S.camp={i,sp:o[3],end:S.d+14}}
function bribe(){if(S.office<1)return;if(!pay(5e6))return;S.tax=Math.max(0,S.tax-.02);if(Math.random()<.25-S.sk.law*.02){S.pop=cl(S.pop-15);S.cash-=1e7;log(' Suap terbongkar! Denda Rp 10 jt, popularitas anjlok')}}
const hs=(a,b,c)=>{let h=(a*73856093)^(b*19349663)^(c*83492791);h=Math.imul(h^(h>>>13),1274126177);return((h^(h>>>16))>>>0)/4294967295};
function comps(b,lv){const t=BT[b.ty],N=['Kuliner','Ritel','Digital','Manufaktur','Kreatif','Trading','Konsultan'][b.ty],P={local:['Maju Jaya','Berkah Abadi','Sumber Rejeki','Mitra Lokal','Cahaya Baru'],nat:['Nusantara Prima','Garuda Mandiri','Indo Sentosa','Bhinneka Utama','Samudra Raya'],glob:['Atlas Global','Meridian Corp','Helix International','Orion Group','Vertex Worldwide']}[lv],M={local:[1.5,3,6,10,16],nat:[60,110,180,260,380],glob:[700,1300,2200,4000,7000]}[lv],mo=S.d/30|0;return P.map((p,i)=>({n:p+' '+N,rev:t[1]*t[3]*14*M[i]*(.8+.4*hs(b.id||1,lv.length*7+i,mo))*S.eco,mg:1-(t[2]+.1)-.12+(hs(i+3,b.ty+1,mo)-.5)*.1}))}
function cmpv(b){const l=b.l,tb=[['local','Lokal'],['nat','Nasional'],['glob','Global']].map(x=>`<button class="b" style="${BMK==x[0]?'background:var(--t);color:var(--bg)':''}" onclick="BMK='${x[0]}';ren()">${x[1]}</button>`).join('');if(!l)return card('Perbandingan Pasar',tb+'<div class="m" style="margin-top:8px">Jalankan bisnis minimal satu hari untuk melihat perbandingan.</div>');
const our={n:b.name+' (Anda)',rev:l.rev,mg:l.rev?(l.pr-l.tax)/l.rev:0,me:1},all=[...comps(b,BMK),our].sort((x,y)=>y.rev-x.rev),mx=all[0].rev||1,rk=all.findIndex(x=>x.me)+1,tot=all.reduce((a,x)=>a+x.rev,0);
const rows=all.map((x,i)=>`<div style="padding:6px 0;border-bottom:1px solid var(--l)"><div style="display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap"><span>${i+1}. <b>${x.n}</b></span><span class="m">${R(x.rev)}/hari · margin ${(x.mg*100).toFixed(0)}%</span></div><div class="bar"><i style="width:${Math.max(1,x.rev/mx*100)}%;background:${x.me?'var(--a)':'var(--m)'}!important"></i></div></div>`).join('');
const nx=rk>1?all[rk-2]:null,msg=nx?'Selisih omzet ke peringkat '+(rk-1)+' ('+nx.n+'): '+R(nx.rev-our.rev)+'/hari.':'Anda memimpin kelompok ini.';
return card('Perbandingan Pasar',tb+'<div style="margin-top:8px">'+rows+'</div>'+row('Peringkat Anda','<b>#'+rk+' dari '+all.length+'</b>')+row('Pangsa omzet kelompok','<b>'+(our.rev/tot*100).toFixed(1)+'%</b>')+'<div class="m">'+msg+' Pesaing bergerak mengikuti kondisi ekonomi. Data diperbarui tiap bulan.</div>')}
const CT=[['sari','Sari','Teman dekat'],['broto','Pak Broto','Kolega kerja'],['ratna','Bu Ratna','Sesama pengusaha'],['hendra','Pak Hendra','Pejabat'],['clarissa','Ibu Clarissa','Investor'],['rafi','Rafi','Tokoh publik']],
CTM={sari:'teman',broto:'rekan',ratna:'usaha',hendra:'pejabat',clarissa:'investor',rafi:'tokoh'},
CO=[['ramah','Santai & ramah, ngobrol seperti biasa'],['formal','Profesional & to the point'],['blak','Blak-blakan, langsung minta bantuan']],
CW={teman:{ramah:2,formal:0,blak:1},rekan:{ramah:1,formal:1,blak:0},usaha:{ramah:0,formal:2,blak:1},pejabat:{ramah:-1,formal:2,blak:-2},investor:{ramah:-1,formal:2,blak:0},tokoh:{ramah:1,formal:0,blak:-1},mentor:{ramah:1,formal:2,blak:-2}},
COPEN={sari:['Eh, lagi apa? Udah lama nggak ngobrol.'],broto:['Halo, gimana kabar kerjaan akhir-akhir ini?'],ratna:['Selamat siang. Usaha lancar?'],hendra:['Ya, ada perlu apa menghubungi saya?'],clarissa:['Hai. Saya dengar kamu sedang mencari peluang.'],rafi:['Yo! Ada yang bisa dibantu?']},
CRP={teman:{2:'Santuy aja kok! Btw kalau butuh apa-apa bilang aja ya.',1:'Oh gitu, oke deh. Semangat terus!',0:'Hehe iya. Formal amat sih, kayak lagi meeting aja.',[-1]:'Hah? Kok serius amat.',[-2]:'Ya ampun, minta bantuan mulu deh kamu.'},
rekan:{2:'Wah asik, ntar kita ngopi bareng lagi ya.',1:'Sip, siap bantu kalau ada yang bisa saya lakukan.',0:'Baik, saya catat. Nanti saya kabari lagi.',[-1]:'Hmm, agak canggung juga ya diomongin gini.',[-2]:'Wih to the point banget, tapi oke saya coba pikirkan.'},
usaha:{2:'Menarik, tapi coba lebih rapi lagi presentasinya lain kali.',1:'Baik, kita bisa bahas lebih lanjut kalau ada waktu.',0:'Terima kasih sudah menghubungi secara profesional. Saya pertimbangkan.',[-1]:'Saya kira ini pertemuan bisnis, bukan reuni.',[-2]:'Ambisius juga ya kamu, tapi belum saatnya.'},
pejabat:{2:'Untuk urusan resmi, silakan lewat jalur yang benar ya.',1:'Baik, catatan Anda akan saya sampaikan ke tim terkait.',0:'Pendekatan yang tepat. Saya akan pertimbangkan permohonan Anda.',[-1]:'Saya rasa kita belum cukup dekat untuk bicara sesantai itu.',[-2]:'Maaf, saya tidak bisa membantu hal seperti itu begitu saja.'},
investor:{2:'Hubungan baik itu penting, tapi saya perlu lihat angkanya juga.',1:'Menarik. Kirimkan saya data usaha Anda ya.',0:'Pendekatan yang profesional. Saya akan pelajari proposal Anda.',[-1]:'Saya lebih suka membahas ini secara formal.',[-2]:'Saya belum yakin, kembalilah setelah usaha Anda lebih matang.'},
tokoh:{2:'Wah asik, kita bisa kolaborasi santai gini kok.',1:'Boleh, nanti saya kirim detail kolaborasinya.',0:'Oke, japri aja kalau ada proposal resmi.',[-1]:'Kaku amat sih, padahal kita kan udah kenal.',[-2]:'Wah langsung minta gitu aja? Santai dong.'},
mentor:{2:'Bagus, sikap terbuka begitu yang bikin cepat belajar.',1:'Oke, saya hargai caramu bertanya.',0:'Nada bicaramu terlalu santai untuk bimbingan seperti ini.',[-1]:'Belajarlah bersikap lebih hormat kepada yang lebih senior.',[-2]:'Kalau maunya instan begitu, saya tidak bisa bantu banyak.'}};
const MK={rekan:['Bertemu rekan / teman',2,1e5,['Dimas','Sari','Bayu','Rina','Andi'],''],usaha:['Sesama pengusaha',2,3e5,['Pak Hendra','Bu Lestari','Koh Anton','Bu Maya'],''],pejabat:['Pejabat / birokrat',3,1e6,['Pak Camat','Bu Kepala Dinas','Pak Sekda','Bu Anggota Dewan'],'butuh popularitas 15 atau jaringan 10'],investor:['Investor',3,1e6,['Pak Wijaya','Bu Clarissa','Mr. Tan','Bu Ratna'],'perlu punya bisnis'],tokoh:['Tokoh masyarakat',2,2e5,['Pak Haji Umar','Bu Ketua Asosiasi','Pak Ketua Adat','Bu Rektor'],''],mentor:['Mentor senior',2,2e5,['Pak Surya','Bu Diana','Prof. Budi','Bu Kartika'],'']},
GR=['Wah, Anda yang sering muncul di media itu, ya? Silakan duduk.','Oh, saya pernah dengar nama Anda. Silakan.','Halo, silakan duduk. Kita belum pernah bertemu, ya?'],
REP={rekan:['Eh, jangan dipaksain. Ngopi dulu, urusan bisnis belakangan.','Utang itu wajar. Yang penting ada rencana bayarnya, nanti kubantu cari peluang.','Semua orang mulai dari nol. Nanti kukenalin ke beberapa orang.','Keren, sudah punya usaha sendiri. Kalau butuh tenaga atau pelanggan, kabari aku.','Sudah sebesar itu jangan lupa teman lama, ya. Traktir dong.'],
usaha:['Pengusaha yang sehat dulu, baru bisnisnya ikut sehat. Jangan tumbang di tengah jalan.','Utang boleh asal produktif. Jangan pakai utang buat gaya hidup.','Belum punya usaha? Mulai kecil, kuasai satu produk, baru melebar.','Ada yang bisa kita kerjakan bareng. Pemasok saya bisa kasih harga bagus.','Di level Anda orang bicara margin dan ekspansi. Ayo bahas kerja sama serius.'],
pejabat:['Kesehatan dulu. Urusan izin kami bantu sesuai aturan.','Kalau ada kewajiban yang belum beres, selesaikan dulu supaya urusan lancar.','Silakan ajukan lewat prosedur. Nama Anda saya catat.','Usaha lokal seperti Anda kami dukung. Ikuti saja aturan yang berlaku.','Usaha sebesar itu berdampak ke lapangan kerja. Kita perlu sering berdiskusi.'],
investor:['Investor melihat pendirinya. Kalau fisik dan pikiran sedang drop, kami tunggu dulu.','Beban utang Anda masih tinggi. Rapikan neraca, baru kita bicara.','Belum ada usaha yang berjalan, jadi belum ada yang bisa kami nilai.','Angka Anda menarik. Kirim laporan keuangan bulan ini.','Skala Anda sudah pantas dibicarakan. Kami tertarik ekspansi bersama.'],
tokoh:['Jaga diri, Nak. Nama baik dibangun pelan-pelan, jangan dengan badan yang sakit.','Utang dibayar, nama baik terjaga. Itu pegangan kami di sini.','Ikut kegiatan warga dulu. Orang percaya pada yang hadir.','Usahamu bermanfaat buat warga, itu yang kami lihat.','Usaha besar punya tanggung jawab besar kepada masyarakat sekitar.'],
mentor:['Istirahat itu strategi, bukan kelemahan. Tidur cukup dulu.','Utang melatih disiplin. Buat jadwal bayar dan patuhi.','Fokus pada satu skill sampai dalam. Belajar, praktik, ulangi.','Delegasikan yang bisa didelegasikan. Tidak semua bisa kamu kelola sendiri.','Di skala ini kerjamu memilih orang, bukan mengerjakan semuanya.']},
UA={rekan:'Kalau ada info atau peluang, kabari saya ya.',usaha:'Menurut Anda, apa kita bisa kerja sama?',pejabat:'Saya berharap urusan izin dan usaha bisa dipermudah.',investor:'Saya sedang mencari mitra pendanaan.',tokoh:'Saya ingin lebih dikenal dan ikut berkontribusi.',mentor:'Nasihat apa yang paling penting untuk saya sekarang?'},
OKL={rekan:'Tentu! Nanti kukabari kalau ada peluang. Ini kontak beberapa orang buat kamu.',usaha:'Boleh. Mari mulai dengan kerja sama kecil dulu, saling untung.',pejabat:'Akan saya coba bantu sesuai kewenangan. Kirim berkasnya ke ajudan saya.',investor:'Saya tertarik. Ini dana awal tanda kepercayaan, kirim prospektusnya.',tokoh:'Datanglah ke acara kami, akan saya kenalkan Anda kepada warga.',mentor:'Baik, ini yang harus kamu pelajari. Kuasai itu dulu.'},
FL={rekan:'Oke, nanti kalau ada aku kabari. Yang penting kita sering ketemu.',usaha:'Belum sekarang, tapi kartu nama Anda saya simpan.',pejabat:'Semua ada prosedurnya. Saya tidak bisa menjanjikan apa-apa hari ini.',investor:'Belum cocok saat ini. Hubungi lagi kalau angka Anda membaik.',tokoh:'Terima kasih sudah bersilaturahmi. Sering-seringlah datang.',mentor:'Kembali lagi kalau sudah menjalankan nasihat tadi.'};
const cst=()=>S.hp<45?'sick':S.str>65?'stress':(S.loan>2e6&&S.loan>nw()*.3)?'debt':S.bizs.some(b=>b.sc>=3)?'big':S.bizs.length?'biz':S.job!=null?'job':'none';
function hint(w){const a=pk(AS),sg=Math.random()<.5?1:-1;S.fx.push({t:a[0],e:(Math.random()<.7?sg:-sg)*.008,d:6});S.news.unshift({d:S.d,t:'Rumor: '+a[1]+(sg>0?' diprediksi naik':' diprediksi turun')+' (info dari '+w+')',c:'Rumor',up:sg>0});return 'Info pasar: '+a[0]+(sg>0?' katanya naik':' katanya turun')+' (belum tentu benar)'}
const WD={rekan:{0:'Duh, kelihatannya kondisi keuanganmu lagi ketat ya.',1:'Hidupmu kelihatannya udah lumayan stabil sekarang.',2:'Wih, kamu makin mapan aja belakangan ini!'},
usaha:{0:'Modal usaha memang selalu jadi tantangan di awal-awal.',1:'Usaha Anda kelihatannya berjalan cukup baik sekarang.',2:'Skala usaha Anda sekarang sudah impresif juga.'},
pejabat:{0:'Kondisi ekonomi Anda akan jadi salah satu pertimbangan kami.',1:'Anda termasuk warga dengan usaha yang cukup stabil.',2:'Kontribusi dari usaha sebesar milik Anda cukup signifikan bagi daerah.'},
investor:{0:'Terus terang, profil keuangan Anda belum terlalu menarik bagi kami.',1:'Fundamental keuangan Anda sudah cukup untuk kami pertimbangkan.',2:'Portofolio Anda menarik perhatian banyak investor, termasuk kami.'},
tokoh:{0:'Yang penting niat baiknya dulu, soal materi belakangan.',1:'Anda sudah cukup mapan untuk mulai ikut berkontribusi ke masyarakat.',2:'Sumbangsih dari orang sesukses Anda akan sangat berarti bagi warga.'},
mentor:{0:'Jangan minder soal keuangan dulu, fokus saja ke kemampuan.',1:'Fondasi keuanganmu sudah oke, tinggal terus dikembangkan.',2:'Di level kekayaanmu sekarang, tantangannya sudah beda lagi.'}},
RWR=['Saya masih berusaha memperbaiki kondisi ini pelan-pelan.','Terima kasih, saya akan terus jaga supaya makin baik.','Terima kasih, saya akan terus kembangkan lagi ke depannya.'],
HW={rekan:'Eh, mukamu pucat gitu, udah periksa ke dokter belum?',usaha:'Jangan dipaksain kalau badan lagi drop, nanti bisnis ikut keteteran.',pejabat:'Jaga kesehatan dulu, Pak/Bu. Urusan resmi bisa menyusul kapan saja.',investor:'Kesehatan pendirinya itu aset penting bagi kami, tolong dijaga baik-baik.',tokoh:'Nak, kesehatan itu nomor satu, baru urusan lain-lain.',mentor:'Istirahat itu bukan kemalasan, tapi investasi jangka panjang.'};
function meet(k){const K=MK[k],ref=k=='pejabat'&&S.pop<15&&S.net<10&&!S.office;if(S.hrs<K[1])return log('Waktu tidak cukup ('+K[1]+' jam)');if(!ref&&S.cash<K[2])return log('Uang tidak cukup untuk bertemu');
const who=pk(K[3]),sx=cst(),gp=S.pop>=50?0:S.pop>=25?1:2;
const uo={sick:'Maaf, badan saya lagi kurang fit, tapi saya sempatkan datang.',stress:'Saya lagi banyak pikiran, tapi senang bisa ngobrol.',debt:'Saya sedang menata utang, jadi butuh relasi yang bisa membantu.',none:'Saya baru mulai, belum punya apa-apa selain semangat.',job:S.job!=null?'Saya masih bekerja sebagai '+JB[S.job][0]+', tapi ingin mulai usaha.':'',biz:'Saya sedang menjalankan '+S.bizs.length+' usaha.',big:'Bisnis saya sudah cukup besar, tantangannya sekarang menjaga arus kas dan orang.'}[sx];
const L=[['T',k=='rekan'?pk(['Halo! Lama nggak ketemu, ya.','Akhirnya bisa ketemu juga!']):GR[gp]],['Anda',uo]];
if(S.hp<35)L.push(['T',HW[k]],['Anda','Terima kasih sudah mengingatkan, saya akan lebih jaga kesehatan.']);
if(ref){L.push(['T','Maaf, jadwal beliau padat. Silakan buat janji lewat sekretaris dulu.'],['Anda','Baik, saya coba lagi nanti.']);S.hrs-=1;S.chat={k,who,role:K[0],d:S.d,lines:L,res:'Ditolak. Butuh popularitas 15 atau jaringan 10.',pending:false};return}
S.cash-=K[2];S.hrs-=K[1];
S.chat={k,who,role:K[0],d:S.d,lines:L,res:null,pending:true,round:0,sum:0};log('Bertemu '+who+' ('+K[0]+')')}
const SOCIAL_ROUNDS=2;
function socialPick(opt){if(!S.chat||!S.chat.pending)return;const k=S.chat.k,g=k,w=CW[g][opt];
S.chat.lines.push(['Anda',CO.find(x=>x[0]==opt)[1]],['T',CRP[g][w]]);S.chat.sum+=w;S.chat.round++;
if(S.chat.round<SOCIAL_ROUNDS){S.chat.lines.push(['T',pk(CFU[g]||CFU.teman)]);return}
const sx=cst(),g2={sick:0,stress:0,debt:1,none:2,job:2,biz:3,big:4}[sx],wt=nw()>=1e9?2:nw()>=1e8?1:0,rich=wt==2?.1:wt==1?.05:0;
let p=cl(.25+S.net/250+S.pop/300+S.sk.com*.03+S.sk.lang*.01+rich-(S.str>65?.15:0)-(S.hp<45?.15:0)-(sx=='debt'?.1:0),.1,.9);if(k=='mentor')p*=.7;if(k=='investor'&&!S.bizs.length)p=0;
const avg=S.chat.sum/SOCIAL_ROUNDS;p=cl(p+avg*.12,.05,.95);
const ok=Math.random()<p,res=[],mu=(S.staff.includes('Sekretaris')?2:1)*(1+S.sk.com*.2+S.sk.lang*.1),ad=(key,v)=>{S[key]=cl(S[key]+v)},an=v=>{ad('net',v*mu);res.push('Jaringan +'+(v*mu).toFixed(1))};
S.chat.lines.push(['T',REP[k][g2]],['Anda',UA[k]],['T',(ok?OKL:FL)[k]],['Anda',ok?'Terima kasih, ini sangat membantu.':'Baik, saya mengerti. Terima kasih atas waktunya.']);
if(k=='rekan'){an(ok?4:2);ad('str',-6);ad('hap',4);res.push('Stres -6','Bahagia +4');if(ok)res.push(hint(S.chat.who))}
else if(k=='usaha'){an(ok?5:3);if(ok){const tt=S.bizs.reduce((a,b)=>a+(b.l?Math.max(0,b.l.pr):0),0),dl=Math.max(5e5,tt*2);S.cash+=dl;res.push('Kerja sama: +'+R(dl))}}
else if(k=='pejabat'){an(ok?5:3);if(ok){if(Math.random()<.5){S.tax=Math.max(0,S.tax-.01);res.push('Pajak bisnis turun 1%')}else{ad('pop',2);res.push('Popularitas +2')}}}
else if(k=='investor'){an(ok?4:2);if(ok){const f=8e6*(1+S.net/20)*SC[Math.max(...S.bizs.map(b=>b.sc))][1]**.6;S.cash+=f;res.push('Dana awal: +'+R(f))}}
else if(k=='tokoh'){ad('pop',ok?6:3);an(2);ad('hap',2);res.push('Popularitas +'+(ok?6:3),'Bahagia +2')}
else{an(1);ad('str',-4);if(ok){const ks=Object.keys(SKN).filter(x=>S.sk[x]<10);if(ks.length){const x=pk(ks);S.sk[x]++;res.push('Skill '+SKN[x]+' naik ke Lv '+S.sk[x])}}else{ad('hap',2);res.push('Bahagia +2')}}
S.chat.res=(ok?'Berhasil: ':'Hasil: ')+res.join(' · ');S.chat.pending=false}
function openShort(id,a){if(!pay(a))return;S.shorts=S.shorts||{};const px=S.px[id],cur=S.shorts[id]||{q:0,val:0,avg:px};cur.avg=(cur.avg*cur.val+px*a)/(cur.val+a);cur.q+=a/px;cur.val+=a;S.shorts[id]=cur;log('Short '+id+' senilai '+R(a));S.thist=S.thist||[];S.thist.unshift('Hari '+S.d+' · Short '+id+' · '+R(a));if(S.thist.length>30)S.thist.length=30}
function closeShort(id,frac){const h=S.shorts&&S.shorts[id];if(!h)return;const px=S.px[id],q=h.q*frac,principal=h.val*frac,pl=(h.avg-px)*q,payout=Math.max(0,principal+pl);S.cash+=payout;h.q-=q;h.val-=principal;if(h.q<1e-9)delete S.shorts[id];log('Tutup short '+id+' · '+(pl>=0?'untung':'rugi')+' '+R(pl));S.thist=S.thist||[];S.thist.unshift('Hari '+S.d+' · Tutup short '+id+' · '+(pl>=0?'+':'')+R(pl));if(S.thist.length>30)S.thist.length=30}
function placeOrder(aid,kind,price,amt){S.orders=S.orders||[];S.oid=(S.oid||0)+1;S.orders.push({id:S.oid,aid,kind,price,amt});log('Order '+(kind=='buy'?'beli':'jual')+' '+aid+' dipasang @ '+R(price))}
function cancelOrder(id){S.orders=(S.orders||[]).filter(o=>o.id!=id)}
function foundBiz(){if(S.bizs.length>=5)return log('Maksimal 5 bisnis boleh berjalan bersamaan. Jual salah satu dulu.');const cap=bcap(NB);if(S.hrs<2)return log('Butuh 2 jam untuk mendirikan bisnis');if(!pay(cap))return;S.hrs-=2;S.bn=(S.bn||0)+1;const nm=(NB.name||'').trim().slice(0,40)||(BT[NB.ty][0]+' #'+S.bn);S.bizs.push({id:S.bn,ty:NB.ty,name:nm,sc:NB.sc,mgmt:NB.mg,price:1,qual:1,mk:0,mg:0});log('Bisnis baru: '+nm+', skala '+SC[NB.sc][0]);NB.name='';BV=S.bizs.length-1}
function renameBiz(i){const b=S.bizs[i];if(!b)return;const v=prompt('Nama baru untuk perusahaan ini:',b.name);if(v==null||!v.trim())return;b.name=v.trim().slice(0,40);log('Bisnis diganti nama menjadi '+b.name)}
function renameUser(){const v=prompt('Nama Anda:',S.uname||'');if(v==null)return;S.uname=v.trim().slice(0,30);ren()}
function mgb(i){const b=S.bizs[i];if(b.mgmt=='ceo'||b.mg)return;if(use(SC[b.sc][3]))b.mg=1}
function mgAll(){S.bizs.forEach((b,i)=>mgb(i))}
function upg(i){const b=S.bizs[i];if(b.sc>=6)return;if(pay((SC[b.sc+1][2]-SC[b.sc][2])*BT[b.ty][5])){b.sc++;if(b.sc>=5)bigNews(b.name+' resmi naik status menjadi bisnis skala '+SC[b.sc][0]+'!','Bisnis',true)}}
function autoUp(i){const b=S.bizs[i];b.auto=b.auto||0;if(b.auto>=5)return;const cost=1e7*(b.auto+1)*BT[b.ty][5]*SC[b.sc][1]**.5;if(pay(cost))b.auto++}
function cloneBiz(i){const b=S.bizs[i];NB.ty=b.ty;NB.sc=b.sc;NB.mg=b.mgmt;BV='new'}
function sellB(i){const b=S.bizs[i];const payout=Math.round(bcap(b)*.6*(b.ipo?1-b.ipo.pct/100:1));S.cash+=payout;log('Menjual '+b.name+' seharga '+R(payout)+(b.ipo?' (dipotong saham publik)':''));S.bizs.splice(i,1);BV=null}
function ipoBiz(i,pct){const b=S.bizs[i];if(!b)return;if(b.sc<2)return log('Bisnis perlu skala Menengah ke atas untuk IPO');if(b.ipo)return log('Bisnis ini sudah IPO');
pct=cl(Math.round(pct||30),10,60);const val=Math.round(bcap(b)*1.4),raise=Math.round(val*pct/100);
S.ipon=(S.ipon||0)+1;b.ipo={ticker:'IPO'+S.ipon,pct,val,px:100,pv:100};S.cash+=raise;
S.ipoHist=S.ipoHist||[];S.ipoHist.unshift('Hari '+S.d+' · IPO '+b.name+' ('+b.ipo.ticker+') · +'+R(raise));if(S.ipoHist.length>15)S.ipoHist.length=15;
log('IPO '+b.name+': '+pct+'% saham publik, dana masuk '+R(raise));bigNews(b.name+' resmi melantai di bursa (IPO) dengan ticker '+b.ipo.ticker+', melepas '+pct+'% saham ke publik dan meraih dana segar '+R(raise)+'!','Bisnis',true)}
function ipoAdjust(i,dp){const b=S.bizs[i];if(!b||!b.ipo)return;const np=cl(b.ipo.pct+dp,10,70);dp=np-b.ipo.pct;if(!dp)return log('Tidak ada perubahan (batas 10%-70%)');
const amt=Math.round(Math.abs(dp)/100*b.ipo.val);
if(dp>0){S.cash+=amt}else{if(!pay(amt))return}
b.ipo.pct=np;log((dp>0?'Melepas':'Membeli balik')+' '+Math.abs(dp).toFixed(0)+'% saham '+b.ipo.ticker+' · '+R(amt))}
function ipoDelist(i){const b=S.bizs[i];if(!b||!b.ipo)return;const cost=Math.round(b.ipo.val*b.ipo.pct/100*1.1);if(!pay(cost))return;log('Delisting '+b.ipo.ticker+', kepemilikan penuh kembali · '+R(cost));delete b.ipo}
const CFU={teman:['Btw, ada cerita seru nggak akhir-akhir ini?','Eh, kamu lagi sibuk apa sih sekarang?','Kabarnya kamu makin jarang keliatan, kenapa?'],
rekan:['Omong-omong, proyek kerja gimana progresnya?','Ada rencana kerja sama baru nggak akhir-akhir ini?','Kudengar tim kamu lagi kejar target, ya?'],
usaha:['Menurut kamu kondisi pasar sekarang gimana?','Ada tantangan besar di usahamu belakangan ini?','Rencana ekspansi ke depan gimana?'],
pejabat:['Ada hal lain terkait perizinan usaha Anda?','Bagaimana pandangan Anda soal kebijakan ekonomi saat ini?','Apa yang bisa kami bantu selanjutnya?'],
investor:['Ceritakan sedikit soal rencana usaha Anda ke depan.','Bagaimana proyeksi Anda untuk beberapa bulan mendatang?','Apa yang membedakan usaha Anda dari yang lain?'],
tokoh:['Apa yang ingin Anda kontribusikan untuk masyarakat?','Bagaimana pandangan Anda soal isu sosial belakangan ini?','Ada program yang ingin Anda dukung?']};

// --- Event dialog acak: muncul saat melakukan kegiatan tertentu ---
(function(){if(document.getElementById('evov'))return;
const css=document.createElement('style');
css.textContent=`#evov{display:none;position:fixed;inset:0;background:rgba(0,0,0,.65);z-index:9999;align-items:center;justify-content:center;padding:16px}
#evov.show{display:flex}
#evbx{background:var(--bg,#fff);color:var(--t,#111);border:1px solid var(--l,#ddd);max-width:340px;width:100%;padding:16px;box-sizing:border-box}
#evbx h4{margin:0 0 2px;font-size:14px}
#evbx .evrole{font-size:11px;color:var(--m,#888);margin-bottom:10px}
#evbx .evln{margin:6px 0;padding:8px 10px;font-size:13px;line-height:1.4;max-width:88%}
#evbx .evln.them{background:var(--l,#f0f0f0)}
#evbx .evln.me{background:var(--t,#111);color:var(--bg,#fff);margin-left:auto}
#evbx .evfx{margin-top:10px;font-size:12px;color:var(--m,#888)}
#evbx button.b{margin-top:12px;width:100%}`;
document.head.appendChild(css);
const d=document.createElement('div');d.id='evov';
d.innerHTML='<div id="evbx"><h4 id="evwho"></h4><div class="evrole" id="evrole"></div><div id="evbody"></div><div class="evfx" id="evfx"></div><button class="b" onclick="document.getElementById(\'evov\').classList.remove(\'show\')">Lanjut</button></div>';
document.body.appendChild(d)})();
function showEvent(who,role,lines,fx){const ov=document.getElementById('evov');if(!ov)return;
$('evwho').textContent=who;$('evrole').textContent=role;
$('evbody').innerHTML=lines.map((l,i)=>`<div class="evln ${i%2==0?'them':'me'}">${l}</div>`).join('');
$('evfx').textContent=fx||'';ov.classList.add('show')}
const EVN={colleague:['Rina','Dimas','Bayu','Sari','Andi'],official:['Pak Hendra','Bu Kepala Dinas','Pak Camat','Bu Anggota Dewan'],investor:['Bu Clarissa','Pak Wijaya','Mr. Tan','Bu Ratna'],friend:['Sari','Dimas','Rafi','Bayu'],mentor:['Pak Surya','Bu Diana','Prof. Budi'],fan:['Seorang penggemar','Netizen','Follower setia'],client:['Bu Wati','Pak Joko','Sdri. Melani','Pak Umar']},
EVR={colleague:'Kolega',official:'Tokoh Penting',investor:'Investor',friend:'Teman',mentor:'Mentor',fan:'Penggemar',client:'Klien'};
const EVD={
ngopi:[['Eh, gimana kerjaan belakangan ini?','Lumayan, lagi coba jaga ritme aja.'],['Kopi di sini enak juga ya.','Iya, jadi langganan gara-gara sering ke sini.'],['Kudengar kamu makin sibuk.','Iya, tapi seru juga banyak yang dikerjain.'],['Kalau ada proyek bareng, ajak-ajak ya.','Siap, pasti aku kabarin duluan.'],['Kamu kelihatan lebih santai sekarang.','Ya, lagi coba nggak buru-buru terus.']],
lobi:[['Ada keperluan apa menemui saya?','Saya ingin membangun relasi baik untuk usaha saya.'],['Saya dengar nama Anda mulai dikenal.','Terima kasih, saya masih terus belajar.'],['Urusan seperti ini sebaiknya lewat jalur resmi.','Baik, saya akan ikuti prosedurnya.'],['Kita lihat dulu perkembangan Anda ke depan.','Siap, saya akan buktikan lewat kerja nyata.']],
inv_ok:[['Angka-angka Anda menarik, saya tertarik masuk.','Terima kasih atas kepercayaannya.'],['Model bisnis ini punya potensi bagus.','Saya akan terus tingkatkan performanya.'],['Baik, saya siapkan dananya sekarang.','Terima kasih banyak, tidak akan mengecewakan.']],
inv_fail:[['Saya rasa belum saatnya, coba lagi nanti.','Baik, saya akan perbaiki dulu.'],['Datanya belum cukup meyakinkan saya.','Terima kasih atas masukannya.'],['Coba perbesar dulu skala usahanya.','Siap, saya akan kerja lebih keras lagi.']],
gig:[['Kerjaannya rapi, makasih ya.','Sama-sama, senang bisa bantu.'],['Lain kali order lagi ke kamu deh.','Boleh banget, tinggal hubungi saya.'],['Cepat juga selesainya.','Saya usahakan selalu tepat waktu.']],
course:[['Latihan tadi sudah mulai kelihatan hasilnya.','Terima kasih, saya akan terus berlatih.'],['Jangan cuma teori, banyakin praktik ya.','Siap, saya coba terapkan langsung.'],['Pertanyaan bagus, coba jelaskan ke teman-teman lain.','Baik, biar makin paham juga.']],
popa:[['Konten kamu keren, aku follow ya!','Wah makasih banyak, semoga bermanfaat.'],['Baru tau kamu, kok baru sekarang ya.','Hehe baru mulai aktif lagi belakangan ini.'],['Terus posting begini ya, seru diikutin.','Siap, bakal rutin update.']],
leis:[['Udah lama ya kita nggak santai bareng gini.','Iya nih, penting juga buat refreshing.'],['Jangan lupa istirahat di tengah kesibukan.','Iya, ini juga lagi coba jaga keseimbangan.'],['Sekali-sekali gini enak juga.','Setuju, bikin kepala lebih ringan.']]
};
function maybeTalk(kind,ch,p){p=p==null?.35:p;if(Math.random()>=p)return;const pool=EVD[kind];if(!pool||!pool.length)return;
const who=pk(EVN[ch]||EVN.friend),lines=pk(pool);showEvent(who,EVR[ch]||'',lines);log('Ngobrol singkat dengan '+who)}

// --- Balai Lelang ---
const COL=[['Lukisan Klasik',8e6,60e6,4,3],['Jam Tangan Antik',5e6,40e6,3,2],['Mobil Klasik',40e6,3e8,8,4],['Vas Kuno Dinasti',10e6,80e6,3,2],['Gitar Legendaris',6e6,50e6,3,3],['Perhiasan Permata',15e6,1.2e8,5,3],['Piala Bersejarah',4e6,25e6,2,2]],
BIDN=['Penawar Anonim','Kolektor Swasta','Investor Asing','Bandar Lelang','Pengusaha Rival','Ibu Sondang','Pak Tirta'];
function aucGen(){const cat=pk(['collect','collect','prop','stock','biz']);let it={id:S.auc.nextId++,cat,end:S.d+3+Math.floor(Math.random()*4),bidder:null,bidderName:'',myBid:0,hist:[]};
if(cat=='collect'){const c=pk(COL);it.name=c[0];it.val=Math.round(rn(c[1],c[2]));it.pop=c[3];it.hap=c[4];it.min=Math.round(it.val*.4)}
else if(cat=='prop'){const i=Math.floor(Math.random()*PR.length);it.pi=i;it.name=PR[i][0]+' (Sitaan)';it.val=Math.round(PR[i][1]*S.pi);it.min=Math.round(it.val*rn(.45,.65))}
else if(cat=='stock'){const a=pk(AS);const qty=Math.round(rn(3,15)*Math.max(1,1e7/a[3]));it.aid=a[0];it.qty=qty;it.name='Blok Saham '+a[0]+' ('+a[1]+')';it.val=Math.round(qty*S.px[a[0]]);it.min=Math.round(it.val*rn(.7,.85))}
else{const ty=Math.floor(Math.random()*BT.length),sc=Math.floor(Math.random()*3);it.ty=ty;it.sc=sc;it.name=BT[ty][0]+' Sitaan · '+SC[sc][0];it.val=Math.round(SC[sc][2]*BT[ty][5]);it.min=Math.round(it.val*rn(.4,.6))}
it.cur=it.min;S.auc.items.push(it);log(' Lelang baru dibuka: '+it.name)}
function aucBid(id,amt){const it=S.auc.items.find(x=>x.id==id);if(!it)return;if(it.mine)return log('Ini barang lelang Anda sendiri, tidak bisa ditawar sendiri');const minNext=Math.max(it.cur+Math.max(1e5,Math.round(it.cur*.03)),it.min);amt=Math.round(amt);if(amt<minNext)return log('Tawaran minimal '+R(minNext));
const extra=amt-(it.bidder=='you'?it.myBid:0);if(!pay(extra))return;it.cur=amt;it.bidder='you';it.myBid=amt;it.bidderName='Anda';it.hist.unshift('Anda menawar '+R(amt));if(it.hist.length>6)it.hist.length=6;log('Menawar '+it.name+' sebesar '+R(amt))}
function aucTick(){S.auc.items.forEach(it=>{if(Math.random()<.5){const inc=Math.max(1e5,Math.round(it.cur*rn(.04,.14))),nb=it.cur+inc;if(nb<=it.val*1.45){if(it.bidder=='you'){S.cash+=it.myBid;it.myBid=0}it.cur=nb;it.bidder='ai';it.bidderName=pk(BIDN);it.hist.unshift(it.bidderName+' menawar '+R(it.cur));if(it.hist.length>6)it.hist.length=6}}});
S.auc.items=S.auc.items.filter(it=>{if(S.d<it.end)return true;
if(it.cat=='sellcol'){if(it.bidder=='ai'){const fee=Math.round(it.cur*.05);S.cash+=it.cur-fee;log('Lelang "'+it.name+'" laku seharga '+R(it.cur)+' (komisi 5%: -'+R(fee)+')');S.auc.hist.unshift({d:S.d,t:it.name,r:'Terjual · '+R(it.cur-fee)+' bersih'})}
else{S.collect.push({name:it.name,val:it.val});log('Lelang "'+it.name+'" tidak laku, barang dikembalikan');S.auc.hist.unshift({d:S.d,t:it.name,r:'Tidak laku, dikembalikan'})}
if(S.auc.hist.length>20)S.auc.hist.length=20;return false}
if(it.bidder=='you'){if(it.cat=='collect'){S.collect.push({name:it.name,val:it.val});S.pop=cl(S.pop+it.pop);S.hap=cl(S.hap+it.hap)}
else if(it.cat=='prop'){S.props.push(it.pi)}
else if(it.cat=='stock'){const h=S.hold[it.aid]||(S.hold[it.aid]={q:0,c:0});h.q+=it.qty;h.c+=it.cur}
else{S.bn=(S.bn||0)+1;S.bizs.push({id:S.bn,ty:it.ty,name:BT[it.ty][0]+' #'+S.bn+' (Sitaan)',sc:it.sc,mgmt:'self',price:1,qual:1,mk:0,mg:0})}
log(' Menang lelang: '+it.name+' seharga '+R(it.cur));S.auc.hist.unshift({d:S.d,t:it.name,r:'Menang · '+R(it.cur)});if(it.val>=1e9)bigNews(uN()+' memenangkan lelang '+it.name+' senilai '+R(it.cur)+'!','Lelang',true)}
else{S.auc.hist.unshift({d:S.d,t:it.name,r:it.bidder?'Kalah, dimenangkan pihak lain seharga '+R(it.cur):'Ditutup tanpa penawar'})}
if(S.auc.hist.length>20)S.auc.hist.length=20;return false});
if(S.auc.items.length<4&&Math.random()<.3)aucGen()}
function sellCollect(i){const c=S.collect[i];if(!c)return;const v=Math.round(c.val*rn(.7,1.1));S.cash+=v;S.collect.splice(i,1);log(' Menjual '+c.name+' seharga '+R(v))}
function listCollect(i,ask){const c=S.collect[i];if(!c)return;ask=Math.round(ask||c.val*.8);if(ask<=0)return alert('Harga tidak valid');
S.collect.splice(i,1);S.auc.items.push({id:S.auc.nextId++,cat:'sellcol',end:S.d+4,bidder:null,bidderName:'',myBid:0,hist:[],name:c.name,val:c.val,min:ask,cur:ask,mine:true});
log('Melelang '+c.name+' dengan harga awal '+R(ask))}

const V={
portfolio(){const a=19+(S.d/365|0),dRem=Math.max(0,41*365-S.d),yRem=Math.floor(dRem/365),mRem=Math.floor((dRem%365)/30);
const head=card('Profil Pemain',row('Nama',(S.uname?'<b>'+S.uname+'</b>':'<span class="m">(belum diisi)</span>')+' '+bt('✎ Ganti Nama','renameUser()'))
+row('Latar belakang','<b>'+(BGN[S.bg]||'-')+'</b>')
+row('Usia sekarang','<b>'+a+' tahun</b> · Hari ke-'+S.d+' ('+DN[S.d%7]+')')
+row('Usia pensiun','<b>60 tahun</b>'+(S.over?(S.retired?' · <span class="p">sudah pensiun</span>':' · <span class="n">permainan berakhir</span>'):' · tersisa ~'+yRem+' th '+mRem+' bln lagi')));
const finc=card('Ringkasan Keuangan',`<div class="g"><div class="s"><small>Kekayaan bersih</small><b>${R(nw())}</b></div><div class="s"><small>Tunai</small><b>${R(S.cash)}</b></div><div class="s"><small>Deposito</small><b>${R(S.dep)}</b></div><div class="s"><small>Utang</small><b class="n">${R(S.loan)}</b></div></div>`+row('Berlian','<b>'+(S.dia||0)+' 💎</b> <span class="m">(1 berlian = '+R(5e6)+', tukar di Bank)</span>'));
const kond=card('Kondisi',bar('Kesehatan',S.hp,'#ef4444')+bar('Bahagia',S.hap,'#22c55e')+bar('Stres',S.str,'#a855f7')+bar('Populer',S.pop,'#f59e0b')+bar('Jaringan',S.net,'#3b82f6'));
const jobp=card('Pekerjaan & Jabatan',row('Pekerjaan tetap',S.job!=null?'<b>'+JB[S.job][0]+'</b>':'<span class="m">Menganggur</span>')+row('Jabatan politik',S.office?'<b>'+OF[S.office-1][0]+'</b>':'<span class="m">Warga biasa</span>'));
const bizp=card('Bisnis ('+S.bizs.length+'/5)',S.bizs.length?S.bizs.map(b=>row(b.name,SC[b.sc][0]+(b.ipo?' · IPO '+b.ipo.ticker:'')+(b.l?' · <span class="'+(b.l.pr-b.l.tax>=0?'up':'dn')+'">'+R(b.l.pr-b.l.tax)+'/hari</span>':''))).join(''):'<span class="m">Belum punya bisnis.</span>');
const propp=card('Properti ('+S.props.length+') & Megaproyek ('+S.megas.length+')',(S.props.length?S.props.map(i=>row(PR[i][0],R(Math.round(PR[i][1]*S.pi)))).join(''):'<span class="m">Belum punya properti.</span>')+(S.megas.length?S.megas.map(i=>row(PM[i][0]+' <span class="m">(megaproyek)</span>',R(PM[i][1]))).join(''):''));
const bondp=card('Obligasi & Investasi',(S.bonds.length?S.bonds.map(b=>row(b.n,R(b.amt))).join(''):'<span class="m">Belum punya obligasi.</span>')+row('Nilai saham/komoditas/kripto',R(AS.reduce((v,x)=>v+(S.hold[x[0]]?S.hold[x[0]].q*S.px[x[0]]:0),0))));
const skp=card('Skill',Object.keys(SKN).map(k=>row(SKN[k],'Lv '+S.sk[k])).join(''));
const staffp=card('Staf ('+S.staff.length+')',S.staff.length?S.staff.map(n=>row(n,'')).join(''):'<span class="m">Belum punya staf.</span>');
const collp=card('Koleksi ('+S.collect.length+')',S.collect.length?S.collect.map(c=>row(c.name,R(c.val))).join(''):'<span class="m">Belum punya koleksi.</span>');
const goalp=card('Sasaran ('+GL.filter(g=>g[1]()).length+'/'+GL.length+')',row('Lihat & kejar detailnya di halaman Sasaran',bt('Buka Sasaran',"location.href='goal.html'")));
return head+finc+kond+jobp+bizp+propp+bondp+skp+staffp+collp+goalp},
news(){const D=['MINGGU','SENIN','SELASA','RABU','KAMIS','JUMAT','SABTU'][S.d%7],mo=['JAN','FEB','MAR','APR','MEI','JUN','JUL','AGU','SEP','OKT','NOV','DES'][(S.d/30|0)%12],yr=2006+(19+(S.d/365|0));
const idx=S.px.BNUS>S.pv.BNUS*.995?'NAIK':S.px.BNUS<S.pv.BNUS*.995?'TURUN':'STABIL';
const top=S.news[0],rest=S.news.slice(1,9);
const head=top?`<div class="hl">${top.t}</div><div class="byline">Oleh Wartawan ${top.c} &nbsp;·&nbsp; ${top.up?'Pasar bereaksi positif':'Pasar bereaksi waspada'}</div><p class="lede"><span class="dc">${top.t[0]}</span>${top.t.slice(1)} dilaporkan pada hari ${top.d}, memicu ${top.up?'optimisme':'kehati-hatian'} di kalangan pelaku pasar. Analis menyarankan investor mencermati pergerakan harga aset terkait dalam beberapa hari mendatang.</p>`:'<div class="hl">Pasar Tenang, Belum Ada Kabar Besar</div><p class="lede"><span class="dc">B</span>elum ada perkembangan berarti hari ini. Tekan Langkah Selanjutnya untuk melihat kabar berikutnya.</p>';
const briefs=rest.map((n,i)=>`<div class="brief"><b>${n.t}</b><span class="m"> — Hari ${n.d}, ${n.c}. Harga terkait ${n.up?'menguat':'melemah'}.</span></div>`).join('')||'<div class="m">Belum ada berita lawas.</div>';
return `<div class="paper"><div class="mh"><div class="mhtop"><span>${D}, ${S.d} ${mo} ${yr}</span><span>EDISI HARI ${S.d}</span><span>Rp 6.000</span></div><h1>TYCOON GAZETTE</h1><div class="mhbot"><span>Indeks BNUS: ${idx}</span><span>Ekonomi: ${(S.eco*100).toFixed(0)}</span><span>Pajak Usaha: ${(S.tax*100).toFixed(0)}%</span></div></div><div class="cols"><div class="lead">${head}</div><div class="side">${briefs}</div></div><div class="m" style="padding:10px 0 4px;border-top:1px solid var(--nl)">Catatan redaksi: sebagian kabar berupa rumor dan bisa keliru.</div></div>`},
exp(){const l=(o,c)=>Object.entries(o).filter(([k,v])=>v>0||c=='p').map(([k,v])=>row(k,`<span class="${c=='n'?'n':'p'}">${R(v)}</span>`)).join('');const ti=Object.values(S.inc).reduce((a,b)=>a+b,0),to=Object.values(S.ex).reduce((a,b)=>a+b,0);
const sel=(k,arr)=>`<select onchange="S.${k}=+this.value;ren()">${arr.map((x,i)=>`<option value="${i}" ${S[k]==i?'selected':''}>${x[0]} (${R(x[1])}/hari)</option>`).join('')}</select>`;
const dn=`<select onchange="S.dn=+this.value;ren()">${DON.map((x,i)=>`<option value="${i}" ${S.dn==i?'selected':''}>${x[0]}</option>`).join('')}</select>`;
const fix=H[S.house][1]+F[S.food][1]+I[S.ins][1]+TR[S.tr][1]+IT[S.it][1]+EN[S.en][1]+LK[S.lk][1]+GM[S.gm][1]+15e3;
return card('Hunian & Kesehatan',row('Tempat tinggal',sel('house',H))+row('Makanan',sel('food',F))+row('Asuransi kesehatan',sel('ins',I))+'<div class="m">Kualitas tinggi menaikkan bahagia dan kesehatan, tapi biayanya naik.</div>')+card('Mobilitas',row('Transportasi',sel('tr',TR))+'<div class="m">Jalan kaki dan angkutan umum memakan 1 jam di hari kerja dan menambah stres. Ojek online dan mobil pribadi menghemat waktu.</div>')+card('Gaya Hidup',row('Internet & pulsa',sel('it',IT))+row('Hiburan',sel('en',EN))+row('Penampilan',sel('lk',LK))+row('Kebugaran',sel('gm',GM))+row('Donasi rutin',dn)+'<div class="m">Internet cepat menaikkan upah freelance. Penampilan dan donasi menambah popularitas pelan-pelan. Gym menurunkan stres.</div>')+card('Ringkasan Biaya',row('Biaya hidup tetap per hari',R(fix))+row('Perkiraan per bulan (30 hari)','<b>'+R(fix*30)+'</b>'))+card('Pengeluaran Hari Terakhir',l(S.ex,'n')+row('<b>Total</b>','<b>'+R(to)+'</b>'))+card('Pemasukan Hari Terakhir',l(S.inc,'p')+row('<b>Total</b>','<b>'+R(ti)+'</b>'))},
skills(){return card('Kursus & Sertifikasi (3 jam, level maks 10)',Object.keys(SKN).map(k=>row(`<b>${SKN[k]}</b> Lv ${S.sk[k]}<div class="m">${SKD[k]}</div>`,bt('Ambil kursus '+R(3e5*(S.sk[k]+1)**1.5),`course('${k}')`,S.sk[k]>=10))).join(''))},
trade(){const tv=AS.reduce((v,a)=>v+(S.hold[a[0]]?S.hold[a[0]].q*S.px[a[0]]:0),0),tc=AS.reduce((v,a)=>v+(S.hold[a[0]]?S.hold[a[0]].c:0),0);
const chgs=AS.map(a=>({id:a[0],ch:(S.px[a[0]]/S.pv[a[0]]-1)*100||0})),best=chgs.reduce((x,y)=>y.ch>x.ch?y:x),worst=chgs.reduce((x,y)=>y.ch<x.ch?y:x),shTot=Object.values(S.shorts).reduce((a,h)=>a+h.val,0);
const summary=card('Portofolio',row('<b>Nilai saham, komoditas & kripto</b>',`${R(tv)} <span class="${tv>=tc?'up':'dn'}">${tv>=tc?'▲':'▼'} ${R(tv-tc)}</span>`)+(shTot?row('Margin short terbuka',R(shTot)):'')+row('Penggerak terbaik hari ini','<span class="up">'+best.id+' ▲'+best.ch.toFixed(2)+'%</span>')+row('Penggerak terlemah','<span class="dn">'+worst.id+' ▼'+Math.abs(worst.ch).toFixed(2)+'%</span>'));
if(TV&&!AS.some(x=>x[0]==TV))TV=null;
if(TV){
const a=AS.find(x=>x[0]==TV),p=S.px[a[0]],h=S.hold[a[0]],ch=(p/S.pv[a[0]]-1)*100||0,pl=h?h.q*p-h.c:0,sh=S.shorts[a[0]],shpl=sh?(sh.avg-p)*sh.q:0,ord=S.orders.filter(o=>o.aid==a[0]);
const back='<div style="margin-bottom:10px">'+bt('← Daftar aset',"TV=null")+'</div>';
const det=card(`${ai(a[0])}${a[0]} <span class="m">${a[1]} · ${a[2]}</span>`,
row(`${R(p)} <span class="${ch>=0?'up':'dn'}">${ch>=0?'▲':'▼'}${Math.abs(ch).toFixed(2)}%</span>`,spark(a[0]))
+(h?row('Posisi: '+h.q.toFixed(4)+' · '+R(h.q*p),`<span class="${pl>=0?'up':'dn'}">${R(pl)}</span>`):'')
+(sh?row('Short: margin '+R(sh.val),`<span class="${shpl>=0?'up':'dn'}">${R(shpl)}</span> `+bt('Tutup','closeShort(\''+a[0]+'\',1)')):'')
+row('Beli',[1e6,5e6,1e7,5e7].map(v=>bt('Rp '+(v/1e6)+'jt',`buy('${a[0]}',${v})`)).join('')+pb(`customAmt(v=>buy('${a[0]}',v))`))
+row('Jual',bt('50%',`sell('${a[0]}',.5)`,!h)+bt('Semua',`sell('${a[0]}',1)`,!h)+pb(`customPct(v=>sell('${a[0]}',v))`))
+row('Short (margin 1x, biaya 0,1%/hari)',bt('Short 1jt',`openShort('${a[0]}',1e6)`)+bt('Short 5jt',`openShort('${a[0]}',5e6)`)+pb(`customAmt(v=>openShort('${a[0]}',v))`))
+(ord.length?ord.map(o=>row((o.kind=='buy'?'Order beli':'Order jual')+' @ '+R(o.price),bt('Batalkan',`cancelOrder(${o.id})`))).join(''):'')
+row('Pasang order otomatis',[[.9,'Beli -10%'],[.95,'Beli -5%'],[1.05,'Jual +5%'],[1.1,'Jual +10%']].map(x=>bt(x[1],`placeOrder('${a[0]}','${x[0]<1?'buy':'sell'}',${(p*x[0]).toFixed(0)},${x[0]<1?1e6:1})`)).join(''))
);
const ihist=S.thist.filter(t=>t.includes(' '+a[0]+' ')).slice(0,8).map(t=>row(t,'')).join('')||'<span class="m">Belum ada transaksi untuk aset ini.</span>';
return summary+back+det+card('Riwayat Transaksi',ihist)+'<div class="m">Fee jual-beli 0,3%. Short: untung kalau harga turun, rugi kalau naik, kena biaya pinjam 0,1%/hari, rugi maksimum sebatas margin. Order otomatis dieksekusi saat harga menyentuh target.</div>'
}
const rowOf=a=>{const p=S.px[a[0]],h=S.hold[a[0]],ch=(p/S.pv[a[0]]-1)*100||0,sh=S.shorts[a[0]],ordn=S.orders.filter(o=>o.aid==a[0]).length;
return `<div class="r" style="cursor:pointer" onclick="TV='${a[0]}';ren()"><div>${ai(a[0])}<b>${a[0]}</b> <span class="m">${a[1]}</span>`
+(h?`<div class="m">Posisi: ${h.q.toFixed(4)} · ${R(h.q*p)}</div>`:'')
+(sh?`<div class="m">Short aktif · margin ${R(sh.val)}</div>`:'')
+(ordn?`<div class="m">${ordn} order menunggu</div>`:'')
+`</div><div style="text-align:right">${R(p)}<br><span class="${ch>=0?'up':'dn'}">${ch>=0?'▲':'▼'}${Math.abs(ch).toFixed(2)}%</span> ›</div></div>`};
const CATS=['Saham','Komoditas','Forex','Kripto'];
const grouped=CATS.map(cat=>{const items=AS.filter(a=>a[2]==cat);return items.length?card(cat,items.map(rowOf).join('')):''}).join('');
const hist=S.thist.slice(0,8).map(t=>row(t,'')).join('')||'<span class="m">Belum ada transaksi.</span>';
return summary+grouped+card('Riwayat Transaksi',hist)+'<div class="m">Klik salah satu aset untuk melihat detail, beli, jual, short, atau memasang order otomatis.</div>'
},
job(){const TN=['Tingkat 1 · Pemula','Tingkat 2 · Menengah','Tingkat 3 · Ahli','Tingkat 4 · Puncak'];
return card('Pekerjaan Tetap (Sen-Jum, 6 jam/hari)',(S.job!=null?row('Anda bekerja sebagai <b>'+JB[S.job][0]+'</b>',bt('Resign','S.job=null')):'')+'<div class="m">Skill di atas syarat menambah gaji 3% per level. Karier satu tingkat setara gajinya, tapi syarat skillnya beda.</div>')+[0,1,2,3].map(t=>card(TN[t],JB.map((j,i)=>[j,i]).filter(x=>x[0][3]==t).map(([j,i])=>{const ok=Object.entries(j[2]).every(([k,v])=>S.sk[k]>=v);return row(`<b>${j[0]}</b> · ${R(j[1])}/hari<div class="m">Syarat: ${Object.entries(j[2]).map(([k,v])=>SKN[k]+' Lv'+v).join(', ')||'-'}</div>`,bt(S.job==i?'Dipilih':'Lamar',`if(S.job==null&&S.d%7<5)S.hrs=Math.max(0,S.hrs-6);S.job=${i}`,!ok||S.job==i))}).join(''))).join('')+card('Kerja Sampingan',row('Ojek online (3 jam)',bt('Kerjakan',"gig('ojek')"))+row('Freelance (3 jam, naik dengan skill Teknologi & Desain)',bt('Kerjakan',"gig('free')"))+row('Jualan online (2 jam)',bt('Kerjakan',"gig('jual')")))},
biz(){const op=(v,c,l)=>`<option value="${v}" ${v==c?'selected':''}>${l}</option>`,sel=(i,k,o)=>`<select onchange="S.bizs[${i}].${k}=+this.value;ren()">${o.map(x=>op(x[0],S.bizs[i][k],x[1])).join('')}</select>`,ns=(k,o,c,num)=>`<select onchange="NB.${k}=${num?'+':''}this.value;ren()">${o.map((x,i)=>op(num?i:x[0],c,x[1])).join('')}</select>`;
const t=BT[NB.ty],c=SC[NB.sc],cap=bcap(NB),tot=S.bizs.reduce((a,b)=>a+(b.l?b.l.pr-b.l.tax:0),0),need=S.bizs.filter(b=>b.mgmt=='self'&&!b.mg).reduce((a,b)=>a+SC[b.sc][3],0);
const form=card('Dirikan Bisnis Baru',row('Nama perusahaan',`<input class="ipt" type="text" maxlength="40" placeholder="${BT[NB.ty][0]+' #'+((S.bn||0)+1)}" value="${(NB.name||'').replace(/"/g,'&quot;')}" oninput="NB.name=this.value">`)+row('Jenis bisnis',ns('ty',BT.map(x=>[0,x[0]+' (skill: '+SKN[x[4]]+')']),NB.ty,1))+row('Skala',ns('sc',SC.map(x=>[0,x[0]+' - '+R(x[2]*t[5])]),NB.sc,1))+row('Kepengurusan',`<select onchange="NB.mg=this.value;ren()">${op('self',NB.mg,'Kelola sendiri ('+c[3]+' jam/hari)')}${op('ceo',NB.mg,'Sewa CEO ('+R(12e4*c[1]**.9)+'/hari)')}</select>`)+row(`Modal <b>${R(cap)}</b> + 2 jam`,bt('Dirikan','foundBiz()',S.cash<cap||S.bizs.length>=5))+(S.bizs.length>=5?'<div class="n" style="margin-top:8px">Sudah mencapai batas maksimal 5 bisnis berjalan bersamaan. Jual salah satu bisnis dulu untuk mendirikan yang baru.</div>':''));
const sum=S.bizs.length?card('Ringkasan',`<div class="g"><div class="s"><small>Jumlah bisnis</small><b>${S.bizs.length}/5</b></div><div class="s"><small>Laba bersih/hari (kemarin)</small><b class="${tot>=0?'up':'dn'}">${R(tot)}</b></div><div class="s"><small>Perlu dikelola hari ini</small><b>${need} jam</b></div></div>`+row('Sisa waktu: '+S.hrs+' jam. Bisnis yang tidak dikelola sendiri berjalan di 60% permintaan.',bt('Kelola semua',"mgAll()",!need))):'';
const det=(b,i)=>{const t=BT[b.ty],c=SC[b.sc],l=b.l,m=c[1],nx=SC[b.sc+1];b.auto=b.auto||0;b.hist=b.hist||[];
const trendMax=Math.max(1,...b.hist.map(Math.abs)),trend=b.hist.length>1?`<svg width="100%" height="34" viewBox="0 0 100 34" preserveAspectRatio="none" style="display:block;margin-top:6px"><polyline points="${b.hist.map((v,k)=>(k/(b.hist.length-1)*100).toFixed(1)+','+(17-v/trendMax*15).toFixed(1)).join(' ')}" fill="none" stroke="var(--${b.hist[b.hist.length-1]>=0?'up':'a'})" stroke-width="1.5" vector-effect="non-scaling-stroke"/><line x1="0" y1="17" x2="100" y2="17" stroke="var(--l)" stroke-width="1"/></svg>`:'<div class="m">Tren laba akan tampil setelah beberapa hari berjalan.</div>';
return card(b.name+' · '+c[0],`<div class="g"><div class="s"><small>Pelanggan/hari</small>${l?l.c:'-'}</div><div class="s"><small>Omzet</small>${l?R(l.rev):'-'}</div><div class="s"><small>Laba bersih</small>${l?`<span class="${l.pr-l.tax>=0?'up':'dn'}">${R(l.pr-l.tax)}</span>`:'-'}</div></div>`+trend+(b.lastEvt?`<div class="m" style="margin-top:6px">Peristiwa terakhir: ${b.lastEvt}</div>`:''))
+card('Operasional',row('Harga jual',sel(i,'price',[[.8,'Murah'],[1,'Normal'],[1.25,'Premium'],[1.5,'Mewah']]))+row('Kualitas produksi',sel(i,'qual',[[1,'Standar'],[2,'Baik'],[3,'Unggulan']]))+row('Marketing',sel(i,'mk',[[0,'Tanpa'],[1,'Aktif ('+R(1e5*m**.8)+'/hari)'],[2,'Agresif ('+R(4e5*m**.8)+'/hari)']]))+row('Kepengurusan',`<select onchange="S.bizs[${i}].mgmt=this.value;ren()">${op('self',b.mgmt,'Kelola sendiri ('+c[3]+' jam/hari)')}${op('ceo',b.mgmt,'Sewa CEO ('+R(12e4*m**.9)+'/hari)')}</select>`)+row(b.mgmt=='ceo'?'<span class="m">Dikelola CEO (efisiensi 95%)</span>':(b.mg?'<span class="m">Sudah dikelola hari ini (+15%)</span>':'<span class="n">Belum dikelola hari ini</span>'),(b.mgmt=='self'?bt('Kelola ('+c[3]+' jam)',`mgb(${i})`,b.mg):'')))
+card('Otomatisasi · Lv '+b.auto+'/5','<div class="m">Setiap level menambah permintaan 6% dan memangkas biaya variabel & tetap. Terpisah dari skala.</div>'+row(b.auto<5?'Upgrade ke Lv '+(b.auto+1)+' ('+R(1e7*(b.auto+1)*t[5]*m**.5)+')':'Otomatisasi maksimum',bt('Upgrade',`autoUp(${i})`,b.auto>=5)))
+card('Skala & Kepemilikan',row('Nama perusahaan: <b>'+b.name+'</b>',bt('Ganti Nama',`renameBiz(${i})`))+row('Skala saat ini: <b>'+c[0]+'</b>',bt(nx?'Naikkan ke '+nx[0]+' ('+R((nx[2]-c[2])*t[5])+')':'Skala maks',`upg(${i})`,!nx))+row('Buka cabang baru sejenis',bt('Buka Cabang',`cloneBiz(${i})`))+row('Jual bisnis ini',bt('Jual ('+R(Math.round(bcap(b)*.6*(b.ipo?1-b.ipo.pct/100:1)))+')'+(b.ipo?' setelah dipotong saham publik':''),`sellB(${i})`)))
+card('IPO & Saham Publik',b.ipo?(`<div class="g"><div class="s"><small>Ticker</small><b>${b.ipo.ticker}</b></div><div class="s"><small>Saham publik</small><b>${b.ipo.pct}%</b></div><div class="s"><small>Harga saham</small><b>${R(b.ipo.px)}</b> <span class="${b.ipo.px>=b.ipo.pv?'up':'dn'}">${b.ipo.px>=b.ipo.pv?'▲':'▼'}</span></div></div>`
+row('Lepas 5% saham lagi (+'+R(Math.round(b.ipo.val*.05))+')',bt('Lepas',`ipoAdjust(${i},5)`,b.ipo.pct>=70))
+row('Beli balik 5% saham ('+R(Math.round(b.ipo.val*.05))+')',bt('Beli Balik',`ipoAdjust(${i},-5)`,b.ipo.pct<=10))
+row('Ubah persentase secara spesifik',pb(`customNum(v=>ipoAdjust(${i},v),'Persentase dilepas (+) atau dibeli balik (-), contoh -10 atau 15',-60,60)`))
+row('Delisting penuh (beli semua saham publik, premi 10%)',bt('Delisting ('+R(Math.round(b.ipo.val*b.ipo.pct/100*1.1))+')',`ipoDelist(${i})`))
+'<div class="m">Laba bersih bisnis ini dibagi ke pemegang saham publik sesuai persentase kepemilikan mereka setiap hari.</div>')
:(b.sc>=2?row('Lepas ke publik dan dapatkan dana segar dari investor pasar',bt('IPO 30% saham (+'+R(Math.round(bcap(b)*1.4*.3))+')',`ipoBiz(${i},30)`)+pb(`customNum(v=>ipoBiz(${i},v),'Persentase saham dilepas',10,60)`))
:'<span class="m">Perlu skala Menengah ke atas untuk melakukan IPO.</span>'))};
const back='<div style="margin-bottom:10px">'+bt('← Daftar bisnis','BV=null')+'</div>';
if(BV==='new')return back+form;
if(BV!=null&&S.bizs[BV])return back+det(S.bizs[BV],BV)+cmpv(S.bizs[BV]);
const list=S.bizs.length?card('Bisnis Anda ('+S.bizs.length+')',S.bizs.map((b,i)=>{const l=b.l,pr=l?l.pr-l.tax:null;return `<div class="r" style="cursor:pointer" onclick="BV=${i};ren()"><div><b>${b.name}</b><div class="m">${SC[b.sc][0]} · ${b.mgmt=='ceo'?'Dikelola CEO':'Kelola sendiri'}${b.mgmt=='self'&&!b.mg?' · <span class="n">belum dikelola</span>':''}</div></div><div style="text-align:right">${pr==null?'<span class="m">baru</span>':`<span class="${pr>=0?'up':'dn'}">${R(pr)}/hari</span>`} ›</div></div>`}).join('')+'<div class="m" style="margin-top:8px">Klik salah satu bisnis untuk mengelolanya.</div>'):card('Bisnis Anda','<span class="m">Belum ada bisnis. Tambahkan yang pertama.</span>');
return '<div style="margin-bottom:10px"><button class="b" style="padding:9px 14px;font-size:12px" '+(S.bizs.length>=5?'disabled':'')+' onclick="BV=\'new\';ren()">+ Tambah bisnis ('+S.bizs.length+'/5)</button></div>'+sum+list},
leis(){return card('Waktu Luang',row(' Hobi (2 jam, Rp 50 rb)',bt('Lakukan',"leis('hobi')"))+row(' Istirahat (4 jam, gratis)',bt('Lakukan',"leis('rest')"))+row(' Olahraga (2 jam, Rp 30 rb)',bt('Lakukan',"leis('gym')"))+row(' Liburan (10 jam penuh, Rp 3 jt)',bt('Berlibur',"leis('lib')")))},
prop(){const back='<div style="margin-bottom:10px">'+bt('← Kembali','PV=null')+'</div>';
const pimg=k=>`<img src="thumb/prop_${k}.jpg" data-n="0" data-id="prop_${k}" alt="" onerror="tf(this)">`;
if(PV=='market')return back+'<div class="pcg">'+PR.map((p,i)=>{const price=Math.round(p[1]*S.pi),rent=Math.round(p[1]*S.pi*p[2]/365);
return `<div class="pcard">${pimg(PRK[i])}<div class="pb"><h3>${p[0]}</h3><div class="m">Harga ${R(price)}</div><div class="m">Sewa ${R(rent)}/hari</div>${bt('Beli Langsung',`buyP(${i})`,S.cash<price)}</div></div>`}).join('')+'</div>';
if(PV=='build')return back+'<div class="pcg">'+PR.map((p,i)=>{const price=Math.round(p[1]*S.pi),cost=Math.round(price*PRB[i][0]),days=PRB[i][1],save=price-cost;
return `<div class="pcard">${pimg(PRK[i])}<div class="pb"><h3>${p[0]}</h3><div class="m">Biaya bangun ${R(cost)} <span class="up">(hemat ${R(save)})</span></div><div class="m">Lama pembangunan ${days} hari</div>${bt('Mulai Bangun',`startBuild(${i})`,S.cash<cost)}</div></div>`}).join('')+'</div>'+'<div class="m">Selama dibangun, properti belum menghasilkan sewa. Selesai otomatis setelah hari yang ditentukan.</div>';
const pimgM=k=>`<img src="thumb/prop_${k}.jpg" data-n="0" data-id="prop_${k}" alt="" onerror="tf(this)">`;
if(PV=='mega')return back+'<div class="pcg">'+PM.map((p,i)=>{const okN=S.net>=p[4],okP=S.pop>=p[5],okO=S.office>=p[6],ok=okN&&okP&&okO;
return `<div class="pcard">${pimgM(p[7])}<div class="pb"><h3>${p[0]}</h3><div class="m">Biaya ${R(p[1])} · sewa ${R(Math.round(p[1]*p[2]/365))}/hari</div><div class="m">Lama pembangunan ${p[3]} hari</div><div class="m ${okN?'up':'n'}">Jaringan ≥${p[4]} (Anda ${Math.round(S.net)})</div><div class="m ${okP?'up':'n'}">Popularitas ≥${p[5]} (Anda ${Math.round(S.pop)})</div><div class="m ${okO?'up':'n'}">Jabatan minimal ${OF[p[6]-1][0]}</div>${bt('Mulai Megaproyek',`startMega(${i})`,!ok||S.cash<p[1])}</div></div>`}).join('')+'</div>'+'<div class="m">Megaproyek butuh jaringan luas, reputasi politik tinggi, dan jabatan resmi — tidak bisa dibeli instan, hanya dibangun.</div>';
const nav=card('Aksi Properti',row('Pasar Properti — beli instan, harga penuh',bt('Buka Pasar Properti',"PV='market'"))+row('Bangun Properti — lebih murah, tapi butuh waktu',bt('Lihat yang Bisa Dibangun',"PV='build'"))+row('Megaproyek Negara — butuh jaringan & jabatan politik',bt('Lihat Megaproyek',"PV='mega'")));
const prog=(S.builds.length||S.megaBuilds.length)?card('Sedang Dibangun',S.builds.map(b=>row(PR[b.ty][0],'<span class="m">selesai '+(b.end-S.d)+' hari lagi</span>')).join('')+S.megaBuilds.map(b=>row(PM[b.ty][0]+' <span class="m">(megaproyek)</span>','<span class="m">selesai '+(b.end-S.d)+' hari lagi</span>')).join('')):'';
const owned=S.props.length?'<div class="pcg">'+S.props.map((i,x)=>{const price=Math.round(PR[i][1]*S.pi),rent=Math.round(PR[i][1]*S.pi*PR[i][2]/365);
return `<div class="pcard">${pimg(PRK[i])}<div class="pb"><h3>${PR[i][0]}</h3><div class="m">Nilai ${R(price)}</div><div class="m">Sewa ${R(rent)}/hari</div>${bt('Jual (fee 3%)',`sellP(${x})`)}</div></div>`}).join('')+'</div>':'<span class="m">Belum ada properti.</span>';
const megaOwned=S.megas.length?card('Megaproyek Milik Anda','<div class="pcg">'+S.megas.map((i,x)=>{const p=PM[i];return `<div class="pcard">${pimgM(p[7])}<div class="pb"><h3>${p[0]}</h3><div class="m">Sewa ${R(Math.round(p[1]*p[2]/365))}/hari</div>${bt('Lepas Hak Kelola (50%)',`sellMega(${x})`)}</div></div>`}).join('')+'</div>'):'';
return nav+prog+card('Properti Milik Anda',owned)+megaOwned},
bond(){return card('Beli Obligasi (kupon tiap 30 hari)',BD.map((b,i)=>row(`<b>${b[0]}</b><div class="m">${b[1]*100}%/thn · ${b[2]} hari · risiko gagal bayar ${b[3]*100}%</div>`,bt('5 jt',`bond(${i},5e6)`)+bt('50 jt',`bond(${i},5e7)`)+pb(`customAmt(v=>bond(${i},v))`))).join(''))+card('Portofolio',S.bonds.length?S.bonds.map(b=>row(b.n+' '+R(b.amt),'<span class="m">jatuh tempo hari '+b.end+'</span>')).join(''):'<span class="m">Kosong.</span>')},
netw(){const cats=['rekan','usaha','pejabat','investor','tokoh','mentor'];
const busy=S.chat&&S.chat.pending;
const btns=cats.map(k=>{const K=MK[k],ref=k=='pejabat'&&S.pop<15&&S.net<10&&!S.office,dis=busy||S.hrs<K[1]||(!ref&&S.cash<K[2]);
return row(`<b>${K[0]}</b><div class="m">${K[1]} jam · ${R(K[2])}${K[4]?' · '+K[4]:''}</div>`,bt('Temui',`meet('${k}')`,dis))}).join('');
const convo=S.chat?(()=>{const bub=S.chat.lines.map(m=>{const me=m[0]=='Anda';return `<div style="display:flex;justify-content:${me?'flex-end':'flex-start'};margin:6px 0"><div style="max-width:82%;padding:8px 11px;background:${me?'var(--t)':'var(--l)'};color:${me?'var(--bg)':'var(--t)'}">${m[1]}</div></div>`}).join('');
const foot=S.chat.pending?row('Putaran '+(S.chat.round+1)+' dari '+SOCIAL_ROUNDS+' · pilih gaya bicara Anda',CO.map(o=>bt(o[0],`socialPick('${o[0]}')`)).join(''))+'<div class="m" style="margin-top:6px">'+CO.map(o=>'<b>'+o[0]+'</b>: '+o[1]).join(' · ')+'</div>':'<div class="m" style="margin-top:8px;padding-top:8px;border-top:1px solid var(--l)">'+S.chat.res+'</div>';
return card((S.chat.pending?'Bertemu dengan ':'Pertemuan dengan ')+S.chat.who+' <span class="m">· '+S.chat.role+' · Hari '+S.chat.d+'</span>',bub+foot)})():card('Belum Ada Pertemuan','<span class="m">Pilih salah satu kegiatan di bawah untuk memulai. Anda akan diajak mengobrol langsung — gaya bicara yang Anda pilih di tiap putaran ikut menentukan hasilnya, selain kondisi Anda saat itu: kesehatan, stres, utang, skala usaha, hingga kekayaan bersih.</span>');
return card('Jaringan Sosial · '+Math.round(S.net)+'/100',bar('Koneksi',S.net,'#3b82f6'))+convo+card('Tindakan Sosial',btns+'<div class="m">Lawan bicara dipilih acak sesuai kategori setiap kali Anda bertemu.</div>')},
pop(){return card('Kepopuleran · '+Math.round(S.pop)+'/100',bar('Reputasi',S.pop,'#f59e0b')+row(' Posting media sosial (1 jam)',bt('Lakukan',"popa('sos')"))+row(' Endorse influencer (Rp 500 rb)',bt('Lakukan',"popa('inf')"))+row(' Sponsor kegiatan amal (1 jam, Rp 5 jt)',bt('Lakukan',"popa('amal')"))+row(' Iklan TV (2 jam, Rp 20 jt)',bt('Lakukan',"popa('tv')"))+'<div class="m">Popularitas menarik pelanggan & dibutuhkan untuk politik. Turun pelan tiap hari.</div>')},
goal(){return card('Sasaran ('+GL.filter(g=>g[1]()).length+'/'+GL.length+')',GL.map(g=>row(g[0],g[1]()?'<span class="p">✔ Selesai</span>':'<span class="m">Belum</span>')).join(''))+card('Hadiah Berlian 💎',row('Berlian Anda saat ini','<b>'+(S.dia||0)+'</b>')+'<div class="m">Selesaikan seluruh sasaran di atas untuk meraih 10 berlian sekaligus. Tukar berlian jadi uang tunai di halaman Bank, 1 berlian = '+R(5e6)+'.</div>'+(S.diaGiven?'<div class="p">✔ Hadiah 10 berlian sudah pernah diraih.</div>':''))},
pol(){return card('Politik · '+(S.office?OF[S.office-1][0]:'Warga biasa'),(S.camp?row('Kampanye '+OF[S.camp.i][0]+' berjalan','<span class="m">Pemilu hari '+S.camp.end+'</span>'):'')+OF.map((o,i)=>row(`<b>${o[0]}</b><div class="m">Popularitas ≥${o[1]}, jaringan ≥${o[2]}, biaya kampanye ${R(o[3])}, gaji ${R(o[4])}/hari</div>`,bt(S.office>i?'Dijabat':'Maju',`runP(${i})`,S.office>i||S.camp||S.pop<o[1]||S.net<o[2]||S.cash<o[3]||(S.office>0&&i<S.office)))).join(''))+card('Kontrol Regulasi (khusus pejabat)',row('Pajak bisnis: '+(S.tax*100).toFixed(0)+'%',bt('Turunkan','S.tax=Math.max(0,S.tax-.02)',!S.office)+bt('Naikkan','S.tax=Math.min(.3,S.tax+.02)',!S.office))+row('Suap kebijakan (Rp 5 jt, pajak -2%, risiko ketahuan 25%)',bt('Suap','bribe()',!S.office)))},
staff(){return card('Staf (bisa dipekerjakan bersamaan)',ST.map(s=>row(`<b>${s[0]}</b> · ${R(s[1])}/hari<div class="m">${s[2]}</div>`,bt(S.staff.includes(s[0])?'Pecat':'Rekrut',`hire('${s[0]}')`))).join(''))},
bank(){const lim=Math.max(5e6,nw()*.5),dia=S.dia||0;return card('Rekening',`<div class="g"><div class="s"><small>Tunai</small>${R(S.cash)}</div><div class="s"><small>Deposito (~${(4+S.sk.fin*.2).toFixed(1)}%/thn)</small>${R(S.dep)}</div><div class="s"><small>Utang</small><span class="n">${R(S.loan)}</span></div><div class="s"><small>Kekayaan bersih</small>${R(nw())}</div></div>`)+card('Deposito',row('Setor',bt('1 jt',"bank('dep',1e6)")+bt('10 jt',"bank('dep',1e7)")+bt('Semua tunai',"bank('dep','all')")+pb("customAmt(v=>bank('dep',v))"))+row('Tarik semua',bt('Tarik',"bank('wd')")))+card('Kredit (batas '+R(lim)+', bunga ~12%/thn)',row('Ajukan pinjaman',bt('10 jt',"bank('loan',1e7)")+bt('100 jt',"bank('loan',1e8)")+bt('1 M',"bank('loan',1e9)")+pb("customAmt(v=>bank('loan',v))"))+row('Bayar cicilan (pakai tunai)',bt('Lunasi/bayar',"bank('pay')")))+card('Tukar Berlian 💎',row('Berlian Anda','<b>'+dia+'</b>')+row('Nilai tukar','1 berlian = '+R(5e6))+(dia>0?row('Tukar ke tunai',bt('Tukar 1',"exchangeDia(1)")+bt('Tukar Semua ('+dia+')',"exchangeDia("+dia+")")+pb("customNum(v=>exchangeDia(v),'Jumlah berlian ditukar',1,"+dia+")")):'<div class="m">Belum punya berlian. Selesaikan seluruh sasaran di halaman Sasaran untuk meraih 10 berlian sekaligus.</div>'))},
lelang(){const CN={collect:'Barang Koleksi',prop:'Properti Sitaan',stock:'Blok Saham',biz:'Bisnis Sitaan',sellcol:'Lelang Anda'};
const items=S.auc.items.length?S.auc.items.map(it=>{
if(it.cat=='sellcol'){const left=it.end-S.d;
return card(it.name+' <span class="m">· '+CN[it.cat]+'</span>',
row('Harga saat ini','<b>'+R(it.cur)+'</b>'+(it.bidderName?' <span class="m">(peminat: '+it.bidderName+')</span>':' <span class="m">(belum ada peminat)</span>'))
+row('Sisa waktu','<b>'+left+' hari lagi</b>')
+(it.hist.length?'<div class="m" style="margin-top:4px">'+it.hist.slice(0,3).join(' · ')+'</div>':'')
+'<div class="m">Barang milik Anda yang sedang dilelang. Anda tidak bisa menawar barang sendiri; hasil bersih (setelah komisi 5%) masuk otomatis bila laku.</div>')}
const minNext=Math.max(it.cur+Math.max(1e5,Math.round(it.cur*.03)),it.min),mine=it.bidder=='you',left=it.end-S.d;
const bids=[minNext,minNext+Math.round(it.min*.3),minNext+Math.round(it.min*.8)];
return card(it.name+' <span class="m">· '+CN[it.cat]+'</span>',
row('Tawaran tertinggi',`<b>${R(it.cur)}</b>`+(it.bidderName?' <span class="m">('+(mine?'Anda memimpin':it.bidderName)+')</span>':' <span class="m">(belum ada penawar)</span>'))
+row('Sisa waktu','<b>'+left+' hari lagi</b>')
+(it.cat=='stock'?row('Jumlah lot',it.qty.toFixed(2)):'')
+(it.cat=='collect'?row('Efek bila menang','Popularitas +'+it.pop+', Bahagia +'+it.hap):'')
+row('Pasang tawaran',bids.map(v=>bt(R(v),`aucBid(${it.id},${v})`)).join('')+pb(`customAmt(v=>aucBid(${it.id},v))`))
+(it.hist.length?'<div class="m" style="margin-top:4px">'+it.hist.slice(0,3).join(' · ')+'</div>':'')
+(mine?'<div class="m">Dana Rp '+R(it.myBid)+' terkunci untuk tawaran ini, otomatis kembali bila kalah.</div>':''))
}).join(''):card('Lelang Aktif','<span class="m">Belum ada barang yang dilelang saat ini. Cek lagi beberapa hari ke depan.</span>');
const coll=S.collect.length?card('Koleksi Anda — Jual atau Lelang',S.collect.map((c,i)=>row(c.name+' · '+R(c.val),
bt('Jual Cepat (instan)','sellCollect('+i+')')
+bt('Lelang (mulai '+R(Math.round(c.val*.8))+')','listCollect('+i+','+Math.round(c.val*.8)+')')
+pb(`customAmt(v=>listCollect(${i},v),'Harga awal lelang (Rp)')`)
)).join('')+'<div class="m">Jual cepat langsung cair harga acak. Lelang butuh 4 hari, harga bisa naik kalau ada peminat, tapi kena komisi 5% dan bisa saja tidak laku.</div>'):'';
const hist=S.auc.hist.length?card('Riwayat Lelang',S.auc.hist.slice(0,10).map(h=>row('Hari '+h.d+' · '+h.t,h.r)).join('')):'';
return card('Balai Lelang','<div class="m">Barang koleksi, properti sitaan, blok saham, dan bisnis sitaan dilelang secara acak selama beberapa hari. Penawar lain bisa menaikkan tawaran kapan saja — pantau terus sebelum lelang ditutup. Dana Anda dikunci selama memimpin dan otomatis dikembalikan bila kalah. Anda juga bisa melelang barang koleksi milik Anda sendiri.</div>')+items+coll+hist}
};
const MS={portfolio:()=>S.uname||'Lihat profil',news:()=>S.news[0]?S.news[0].t.slice(0,26):'kosong',exp:()=>R(Object.values(S.ex).reduce((a,b)=>a+b,0))+'/hari',skills:()=>'Total Lv '+Object.values(S.sk).reduce((a,b)=>a+b,0),trade:()=>R(AS.reduce((v,a)=>v+(S.hold[a[0]]?S.hold[a[0]].q*S.px[a[0]]:0),0)),job:()=>S.job!=null?JB[S.job][0]:'Menganggur',biz:()=>S.bizs.length+' bisnis',leis:()=>'Stres '+Math.round(S.str),prop:()=>S.props.length+' unit',bond:()=>S.bonds.length+' aktif',netw:()=>Math.round(S.net)+'/100'+(S.chat&&S.chat.pending?' · sedang bertemu':''),pop:()=>Math.round(S.pop)+'/100',goal:()=>GL.filter(g=>g[1]()).length+'/'+GL.length,pol:()=>S.office?OF[S.office-1][0]:'Warga',staff:()=>S.staff.length+' orang',bank:()=>'Utang '+R(S.loan),lelang:()=>S.auc.items.length+' aktif'};
const IC={"portfolio":"M12 3a4 4 0 100 8 4 4 0 000-8M4 21c0-4.4 3.6-8 8-8s8 3.6 8 8","news": "M4 5h16v14H4zM8 9h5M8 13h8M8 16h8", "exp": "M6 3h12v18l-3-2-3 2-3-2-3 2zM9 8h6M9 12h6", "skills": "M2 9l10-5 10 5-10 5zM6 11.5V16c0 1 3 2.5 6 2.5s6-1.5 6-2.5v-4.5", "trade": "M3 20h18M5 15l4-4 3 3 6-7M14 7h4v4", "job": "M3 8h18v11H3zM9 8V5h6v3M3 13h18", "biz": "M3 20V11l6 3.5V11l6 3.5V5h3v15zM3 20h18", "leis": "M12 8a4 4 0 100 8 4 4 0 000-8M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2", "prop": "M3 11l9-8 9 8M5 10v10h14V10M10 20v-6h4v6", "bond": "M4 4h16v13H4zM8 9h8M8 12h5M9 17v4l3-1.5 3 1.5v-4", "netw": "M12 4a2.5 2.5 0 100 5 2.5 2.5 0 000-5M5 15a2.5 2.5 0 100 5 2.5 2.5 0 000-5M19 15a2.5 2.5 0 100 5 2.5 2.5 0 000-5M11 9l-5 6M13 9l5 6M7.5 17.5h9", "pop": "M12 3l2.7 5.6 6.1.9-4.4 4.3 1 6.1L12 17l-5.4 2.9 1-6.1L3.2 9.5l6.1-.9z", "goal": "M12 3a9 9 0 100 18 9 9 0 000-18M12 8a4 4 0 100 8 4 4 0 000-8M12 11.5v1", "pol": "M3 9l9-5 9 5zM5 9v9M9.5 9v9M14.5 9v9M19 9v9M3 20h18", "staff": "M9 11a3 3 0 100-6 3 3 0 000 6M3 20c0-3.5 2.5-6 6-6s6 2.5 6 6M16 6a3 3 0 010 6M18 14c2 .8 3 3 3 6", "bank": "M4 7c0-1.7 3.6-3 8-3s8 1.3 8 3-3.6 3-8 3-8-1.3-8-3zM4 7v5c0 1.7 3.6 3 8 3s8-1.3 8-3V7M4 12v5c0 1.7 3.6 3 8 3s8-1.3 8-3v-5", "lelang": "M4 21h8M8 17l5-5M9 9l5-5 5 5-5 5zM17 4l3 3"};
const IA={USDIDR:'M12 3v18M8 7c0-1.5 1.5-2.5 4-2.5s4 1 4 2.5-1.5 2-4 2.5-4 1-4 2.5 1.5 2.5 4 2.5 4-1 4-2.5',EURIDR:'M14 5a7 7 0 100 14M6 10h9M6 14h7',SGDIDR:'M12 3v18M8 7c0-1.5 1.5-2.5 4-2.5s4 1 4 2.5-1.5 2-4 2.5-4 1-4 2.5 1.5 2.5 4 2.5 4-1 4-2.5',BRPT:'M4 21V9l8-6 8 6v12M9 21v-6h6v6',SOL:'M5 8h11l3-3H8zM5 16h11l3-3H8zM5 12h14',"BNUS": "M3 9l9-5 9 5zM5 9v9M9.5 9v9M14.5 9v9M19 9v9M3 20h18", "TLKM": "M12 11v10M8 21h8M12 11l-4 10M12 11l4 10M8.5 7.5a5 5 0 017 0M6 5a8.5 8.5 0 0112 0", "GOTO": "M6 14a3 3 0 100 6 3 3 0 000-6M18 14a3 3 0 100 6 3 3 0 000-6M9 17h6l-2-6H9M13 11l2-3h3", "ANTM": "M4 9c4-5 12-5 16 0M12 6l1 14M10 20h5", "XAU": "M6 9h12l3 8H3zM9 9l-1.5 8M15 9l1.5 8", "OIL": "M12 3s6 6.5 6 11a6 6 0 01-12 0c0-4.5 6-11 6-11z", "KPI": "M5 8h11v6a5 5 0 01-5 5H10a5 5 0 01-5-5zM16 10h2a2 2 0 010 4h-2M8 3v2M11 3v2", "BTC": "M12 3a9 9 0 100 18 9 9 0 000-18M10 8v8M10 8h3a2 2 0 010 4h-3M10 12h3.5a2 2 0 010 4H10M11 6v2M13 6v2M11 16v2M13 16v2", "ETH": "M12 3l6 9-6 9-6-9zM6 12l6 3 6-3M12 3v12"};
const sv_=(d,z,x)=>`<svg viewBox="0 0 24 24" width="${z}" height="${z}" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="square" stroke-linejoin="miter" ${x||''}><path d="${d}"/></svg>`;
const ai=id=>sv_(IA[id],26,'style="float:left;margin:2px 10px 0 0"');
function tf(e){const x=['jpg','jpeg','png','webp'],n=+e.dataset.n+1;if(n<x.length){e.dataset.n=n;e.src='thumb/'+e.dataset.id+'.'+x[n]}else e.remove()}
function customAmt(cb,label){const v=prompt((label||'Masukkan jumlah (Rp)')+':');if(v==null)return;const n=Math.round(parseFloat(String(v).replace(/[^0-9.]/g,'')));if(!n||n<=0)return alert('Jumlah tidak valid');cb(n)}
function customPct(cb){const v=prompt('Jual berapa persen dari posisi? (1-100):');if(v==null)return;const n=parseFloat(v);if(!n||n<=0||n>100)return alert('Masukkan angka 1-100');cb(n/100)}
function customNum(cb,label,min,max){const v=prompt(label+':');if(v==null)return;const n=parseFloat(v);if(isNaN(n)||(min!=null&&n<min)||(max!=null&&n>max))return alert('Masukkan angka'+(min!=null?' antara '+min+' dan '+max:''));cb(n)}
const pb=expr=>`<button class="b sqb" onclick="${expr};ren()">+</button>`;
let lt=null;
const spark=id=>{const h=(S.hist&&S.hist[id])||[];if(h.length<2)return'';const mn=Math.min(...h),mx=Math.max(...h),w=96,hh=30,g=mx-mn||1,pts=h.map((v,k)=>(k/(h.length-1)*w).toFixed(1)+','+(hh-2-(v-mn)/g*(hh-4)).toFixed(1)).join(' '),up=h[h.length-1]>=h[0];return `<svg width="${w}" height="${hh}" viewBox="0 0 ${w} ${hh}" style="vertical-align:middle;margin-right:6px"><polyline points="${pts}" fill="none" stroke="var(--${up?'up':'a'})" stroke-width="1.5" stroke-linejoin="round"/></svg>`};
function paintStats(){const a=19+(S.d/365|0),d=S.d%365;if($('dt'))$('dt').textContent=(S.uname?S.uname+' · ':'')+'Usia '+a+' th '+((d/30)|0)+' bln · Hari '+S.d+' ('+DN[S.d%7]+')';
if($('top'))$('top').innerHTML=`<div class="s"><small>Tunai</small><b>${R(S.cash)}</b></div><div class="s"><small>Kekayaan</small><b>${R(nw())}</b></div><div class="s"><small>Waktu tersisa</small><b>${S.hrs} jam</b></div>`+bar('Kesehatan',S.hp,'#ef4444')+bar('Bahagia',S.hap,'#22c55e')+bar('Stres',S.str,'#a855f7')+bar('Populer',S.pop,'#f59e0b')+bar('Jaringan',S.net,'#3b82f6');
if($('logs'))$('logs').innerHTML=S.logs.slice(0,3).join('<br>');}
function hubGrid(){return T.map(t=>`<button class="mi" onclick="location.href='${t[0]}.html'">${sv_(IC[t[0]],30)}<b>${t[2]}</b><span>${MS[t[0]]()}</span></button>`).join('')}
